// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mojo/geom/geom.proto

package geom

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Geometry struct {
	// Types that are valid to be assigned to Geometry:
	//	*Geometry_Point
	//	*Geometry_MultiPoint
	//	*Geometry_LineString
	//	*Geometry_MultiLineString
	//	*Geometry_Polygon
	//	*Geometry_MultiPolygon
	//	*Geometry_GeometryCollection
	Geometry             isGeometry_Geometry `protobuf_oneof:"geometry"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-" gorm:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte              `json:"-" gorm:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32               `json:"-" gorm:"-" xml:"-" bson:"-"`
}

func (m *Geometry) Reset()         { *m = Geometry{} }
func (m *Geometry) String() string { return proto.CompactTextString(m) }
func (*Geometry) ProtoMessage()    {}
func (*Geometry) Descriptor() ([]byte, []int) {
	return fileDescriptor_fab2418537ce34be, []int{0}
}
func (m *Geometry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Geometry.Unmarshal(m, b)
}
func (m *Geometry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Geometry.Marshal(b, m, deterministic)
}
func (m *Geometry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Geometry.Merge(m, src)
}
func (m *Geometry) XXX_Size() int {
	return xxx_messageInfo_Geometry.Size(m)
}
func (m *Geometry) XXX_DiscardUnknown() {
	xxx_messageInfo_Geometry.DiscardUnknown(m)
}

var xxx_messageInfo_Geometry proto.InternalMessageInfo

type isGeometry_Geometry interface {
	isGeometry_Geometry()
}

type Geometry_Point struct {
	Point *Point `protobuf:"bytes,1,opt,name=point,proto3,oneof" json:"point,omitempty"`
}
type Geometry_MultiPoint struct {
	MultiPoint *MultiPoint `protobuf:"bytes,2,opt,name=multi_point,json=multiPoint,proto3,oneof" json:"multiPoint,omitempty"`
}
type Geometry_LineString struct {
	LineString *LineString `protobuf:"bytes,3,opt,name=line_string,json=lineString,proto3,oneof" json:"lineString,omitempty"`
}
type Geometry_MultiLineString struct {
	MultiLineString *MultiLineString `protobuf:"bytes,4,opt,name=multi_line_string,json=multiLineString,proto3,oneof" json:"multiLineString,omitempty"`
}
type Geometry_Polygon struct {
	Polygon *Polygon `protobuf:"bytes,5,opt,name=polygon,proto3,oneof" json:"polygon,omitempty"`
}
type Geometry_MultiPolygon struct {
	MultiPolygon *MultiPolygon `protobuf:"bytes,6,opt,name=multi_polygon,json=multiPolygon,proto3,oneof" json:"multiPolygon,omitempty"`
}
type Geometry_GeometryCollection struct {
	GeometryCollection *GeometryCollection `protobuf:"bytes,7,opt,name=geometry_collection,json=geometryCollection,proto3,oneof" json:"geometryCollection,omitempty"`
}

func (*Geometry_Point) isGeometry_Geometry()              {}
func (*Geometry_MultiPoint) isGeometry_Geometry()         {}
func (*Geometry_LineString) isGeometry_Geometry()         {}
func (*Geometry_MultiLineString) isGeometry_Geometry()    {}
func (*Geometry_Polygon) isGeometry_Geometry()            {}
func (*Geometry_MultiPolygon) isGeometry_Geometry()       {}
func (*Geometry_GeometryCollection) isGeometry_Geometry() {}

func (m *Geometry) GetGeometry() isGeometry_Geometry {
	if m != nil {
		return m.Geometry
	}
	return nil
}

func (m *Geometry) GetPoint() *Point {
	if x, ok := m.GetGeometry().(*Geometry_Point); ok {
		return x.Point
	}
	return nil
}

func (m *Geometry) GetMultiPoint() *MultiPoint {
	if x, ok := m.GetGeometry().(*Geometry_MultiPoint); ok {
		return x.MultiPoint
	}
	return nil
}

func (m *Geometry) GetLineString() *LineString {
	if x, ok := m.GetGeometry().(*Geometry_LineString); ok {
		return x.LineString
	}
	return nil
}

func (m *Geometry) GetMultiLineString() *MultiLineString {
	if x, ok := m.GetGeometry().(*Geometry_MultiLineString); ok {
		return x.MultiLineString
	}
	return nil
}

func (m *Geometry) GetPolygon() *Polygon {
	if x, ok := m.GetGeometry().(*Geometry_Polygon); ok {
		return x.Polygon
	}
	return nil
}

func (m *Geometry) GetMultiPolygon() *MultiPolygon {
	if x, ok := m.GetGeometry().(*Geometry_MultiPolygon); ok {
		return x.MultiPolygon
	}
	return nil
}

func (m *Geometry) GetGeometryCollection() *GeometryCollection {
	if x, ok := m.GetGeometry().(*Geometry_GeometryCollection); ok {
		return x.GeometryCollection
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Geometry) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Geometry_Point)(nil),
		(*Geometry_MultiPoint)(nil),
		(*Geometry_LineString)(nil),
		(*Geometry_MultiLineString)(nil),
		(*Geometry_Polygon)(nil),
		(*Geometry_MultiPolygon)(nil),
		(*Geometry_GeometryCollection)(nil),
	}
}

type GeometryCollection struct {
	Type                 string      `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Geometries           []*Geometry `protobuf:"bytes,5,rep,name=geometries,proto3" json:"geometries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-" gorm:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte      `json:"-" gorm:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32       `json:"-" gorm:"-" xml:"-" bson:"-"`
}

func (m *GeometryCollection) Reset()         { *m = GeometryCollection{} }
func (m *GeometryCollection) String() string { return proto.CompactTextString(m) }
func (*GeometryCollection) ProtoMessage()    {}
func (*GeometryCollection) Descriptor() ([]byte, []int) {
	return fileDescriptor_fab2418537ce34be, []int{1}
}
func (m *GeometryCollection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeometryCollection.Unmarshal(m, b)
}
func (m *GeometryCollection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeometryCollection.Marshal(b, m, deterministic)
}
func (m *GeometryCollection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeometryCollection.Merge(m, src)
}
func (m *GeometryCollection) XXX_Size() int {
	return xxx_messageInfo_GeometryCollection.Size(m)
}
func (m *GeometryCollection) XXX_DiscardUnknown() {
	xxx_messageInfo_GeometryCollection.DiscardUnknown(m)
}

var xxx_messageInfo_GeometryCollection proto.InternalMessageInfo

func (m *GeometryCollection) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *GeometryCollection) GetGeometries() []*Geometry {
	if m != nil {
		return m.Geometries
	}
	return nil
}

func init() {
	proto.RegisterType((*Geometry)(nil), "mojo.geom.Geometry")
	proto.RegisterType((*GeometryCollection)(nil), "mojo.geom.GeometryCollection")
}

func init() { proto.RegisterFile("mojo/geom/geom.proto", fileDescriptor_fab2418537ce34be) }

var fileDescriptor_fab2418537ce34be = []byte{
	// 464 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x94, 0xc1, 0x6e, 0xd3, 0x30,
	0x18, 0xc7, 0x17, 0xd6, 0x6e, 0xeb, 0x57, 0x60, 0xcc, 0x5d, 0x37, 0x93, 0x51, 0x52, 0x76, 0x40,
	0x3b, 0x40, 0x22, 0x8d, 0x23, 0xe2, 0x12, 0x84, 0xe0, 0xc0, 0xa4, 0xaa, 0xdc, 0x7a, 0xa9, 0x58,
	0x65, 0x19, 0x8f, 0x38, 0x8e, 0x32, 0xef, 0x90, 0x67, 0xe0, 0x05, 0x78, 0xba, 0x5c, 0xb8, 0xe5,
	0x1d, 0x90, 0x90, 0x9d, 0x34, 0xb6, 0x6b, 0x2e, 0x91, 0xfc, 0xff, 0xff, 0xfd, 0xfb, 0xdc, 0xcf,
	0xfe, 0x0a, 0xa7, 0x5c, 0xdc, 0x89, 0x84, 0x12, 0xc1, 0xf5, 0x27, 0x2e, 0x4a, 0x21, 0x05, 0x1a,
	0x29, 0x35, 0x56, 0x42, 0x78, 0x61, 0x02, 0x19, 0xcb, 0xc9, 0xfa, 0x5e, 0x96, 0x2c, 0xa7, 0x6d,
	0x2e, 0x7c, 0x65, 0x4c, 0xfe, 0x90, 0x49, 0xb6, 0xf6, 0x23, 0x17, 0xbb, 0x91, 0x42, 0xb0, 0x5c,
	0x76, 0xe6, 0xcc, 0x37, 0xb3, 0x8a, 0x8a, 0xbc, 0xb3, 0xa7, 0xc6, 0xb6, 0x77, 0x9d, 0xdb, 0xb2,
	0x95, 0xbf, 0xfc, 0x3b, 0x80, 0xa3, 0xcf, 0x44, 0x70, 0x22, 0xcb, 0x0a, 0x7d, 0x80, 0xa1, 0xde,
	0x84, 0x83, 0x79, 0x70, 0x35, 0xbe, 0x7e, 0x16, 0xf7, 0xbf, 0x29, 0x5e, 0x28, 0x3d, 0x9d, 0x34,
	0x75, 0x74, 0xac, 0x23, 0x6f, 0x04, 0x67, 0x92, 0xf0, 0x42, 0x56, 0x5f, 0xf6, 0x96, 0xed, 0x2e,
	0xb4, 0x84, 0xb1, 0x75, 0x5e, 0xfc, 0x48, 0x43, 0xa6, 0x16, 0xe4, 0x46, 0xb9, 0x2d, 0x09, 0x37,
	0x75, 0x74, 0xca, 0xfb, 0xb5, 0x83, 0x03, 0xa3, 0x2b, 0xa6, 0xd5, 0x20, 0xbc, 0xef, 0x31, 0xbf,
	0xb2, 0x9c, 0x7c, 0xd3, 0x66, 0xcb, 0xcc, 0xfa, 0xb5, 0xcb, 0x34, 0x3a, 0xa2, 0x70, 0xe2, 0xb5,
	0x1e, 0x0f, 0x34, 0x39, 0xdc, 0x3d, 0xad, 0x85, 0x9f, 0x35, 0x75, 0xf4, 0x9c, 0xbb, 0xa2, 0x53,
	0xe3, 0x78, 0xc7, 0x44, 0x9f, 0xe0, 0xb0, 0xeb, 0x36, 0x1e, 0x6a, 0x3c, 0x72, 0x3a, 0xaa, 0x9d,
	0x74, 0xda, 0xd4, 0xd1, 0x49, 0x17, 0x73, 0x70, 0xdb, 0xbd, 0x68, 0x05, 0x4f, 0x9c, 0xab, 0xc6,
	0x07, 0x1a, 0x76, 0xee, 0x77, 0xb6, 0x25, 0x86, 0x4d, 0x1d, 0x9d, 0x71, 0x4b, 0x71, 0xb0, 0x8f,
	0x6d, 0x07, 0x95, 0x30, 0xa1, 0xdd, 0xf5, 0xaf, 0x37, 0x22, 0xcb, 0xc8, 0x46, 0x32, 0x91, 0xe3,
	0x43, 0x5d, 0x61, 0x66, 0x55, 0xd8, 0x3e, 0x92, 0x8f, 0x7d, 0x28, 0x9d, 0x37, 0x75, 0xf4, 0x82,
	0x7a, 0xba, 0x53, 0x0d, 0xf9, 0x7e, 0x0a, 0x70, 0xb4, 0x55, 0x2f, 0x7f, 0x05, 0x80, 0x7c, 0x34,
	0x7a, 0x0d, 0x03, 0x59, 0x15, 0x44, 0x3f, 0xc4, 0x51, 0x8a, 0x9a, 0x3a, 0x7a, 0xaa, 0xd6, 0x06,
	0xbd, 0xd4, 0x3e, 0xba, 0x01, 0xe8, 0x50, 0x8c, 0xdc, 0xe3, 0xe1, 0x7c, 0xff, 0x6a, 0x7c, 0x3d,
	0xf9, 0xcf, 0xa9, 0xdb, 0xb7, 0x61, 0xa2, 0x16, 0xc8, 0x02, 0xa4, 0xab, 0xdf, 0x7f, 0x5e, 0xee,
	0xc1, 0x99, 0x28, 0xa9, 0x66, 0x64, 0xdf, 0x73, 0x6a, 0x60, 0xe9, 0x48, 0xd1, 0x16, 0x6a, 0x6c,
	0x16, 0xc1, 0x2a, 0xa1, 0x4c, 0xfe, 0x78, 0xb8, 0x8d, 0x37, 0x6a, 0x10, 0xc5, 0x9d, 0x78, 0xab,
	0xc2, 0xdd, 0xbf, 0x82, 0x48, 0x8a, 0x9f, 0x34, 0xe9, 0x47, 0xee, 0xbd, 0xfa, 0xdc, 0x1e, 0xe8,
	0x81, 0x7b, 0xf7, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x82, 0x1c, 0x3d, 0xf7, 0x3f, 0x04, 0x00, 0x00,
}
