// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mojo/geom/line_string.proto

package geom

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type LineString struct {
	Type                 string    `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Coordinates          []*LngLat `protobuf:"bytes,5,rep,name=coordinates,proto3" json:"coordinates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LineString) Reset()         { *m = LineString{} }
func (m *LineString) String() string { return proto.CompactTextString(m) }
func (*LineString) ProtoMessage()    {}
func (*LineString) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c69b72e771f2878, []int{0}
}
func (m *LineString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LineString.Unmarshal(m, b)
}
func (m *LineString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LineString.Marshal(b, m, deterministic)
}
func (m *LineString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LineString.Merge(m, src)
}
func (m *LineString) XXX_Size() int {
	return xxx_messageInfo_LineString.Size(m)
}
func (m *LineString) XXX_DiscardUnknown() {
	xxx_messageInfo_LineString.DiscardUnknown(m)
}

var xxx_messageInfo_LineString proto.InternalMessageInfo

func (m *LineString) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *LineString) GetCoordinates() []*LngLat {
	if m != nil {
		return m.Coordinates
	}
	return nil
}

type LineStringCoordinates struct {
	Values               []*PointCoordinates `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *LineStringCoordinates) Reset()         { *m = LineStringCoordinates{} }
func (m *LineStringCoordinates) String() string { return proto.CompactTextString(m) }
func (*LineStringCoordinates) ProtoMessage()    {}
func (*LineStringCoordinates) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c69b72e771f2878, []int{1}
}
func (m *LineStringCoordinates) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LineStringCoordinates.Unmarshal(m, b)
}
func (m *LineStringCoordinates) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LineStringCoordinates.Marshal(b, m, deterministic)
}
func (m *LineStringCoordinates) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LineStringCoordinates.Merge(m, src)
}
func (m *LineStringCoordinates) XXX_Size() int {
	return xxx_messageInfo_LineStringCoordinates.Size(m)
}
func (m *LineStringCoordinates) XXX_DiscardUnknown() {
	xxx_messageInfo_LineStringCoordinates.DiscardUnknown(m)
}

var xxx_messageInfo_LineStringCoordinates proto.InternalMessageInfo

func (m *LineStringCoordinates) GetValues() []*PointCoordinates {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
	proto.RegisterType((*LineString)(nil), "mojo.geom.LineString")
	proto.RegisterType((*LineStringCoordinates)(nil), "mojo.geom.LineStringCoordinates")
}

func init() { proto.RegisterFile("mojo/geom/line_string.proto", fileDescriptor_4c69b72e771f2878) }

var fileDescriptor_4c69b72e771f2878 = []byte{
	// 278 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x4f, 0x4b, 0xc3, 0x30,
	0x18, 0xc6, 0x29, 0xea, 0x60, 0x19, 0xf8, 0xa7, 0x58, 0xad, 0xdb, 0xa1, 0x63, 0x07, 0xd9, 0x41,
	0x1b, 0xd0, 0xa3, 0xb7, 0x78, 0x12, 0x8a, 0x14, 0xbd, 0x89, 0x30, 0xd2, 0x19, 0x62, 0xb4, 0xc9,
	0x1b, 0xda, 0x4c, 0xd8, 0xdd, 0xcf, 0xd9, 0x0f, 0xd0, 0x4f, 0x31, 0x92, 0x8e, 0x25, 0x97, 0x40,
	0xf2, 0xfc, 0xde, 0xe7, 0x79, 0xf3, 0xa0, 0x99, 0x84, 0x1f, 0xc0, 0x9c, 0x81, 0xc4, 0xb5, 0x50,
	0x6c, 0xd5, 0x9a, 0x46, 0x28, 0x9e, 0xeb, 0x06, 0x0c, 0xc4, 0x63, 0x2b, 0xe6, 0x56, 0x9c, 0x5e,
	0x07, 0x9c, 0xe2, 0xab, 0x9a, 0x9a, 0x81, 0x99, 0x26, 0x5e, 0xd0, 0x20, 0xd4, 0xfe, 0x79, 0xf1,
	0x1f, 0x21, 0x54, 0x08, 0xc5, 0xde, 0x9d, 0x5f, 0x7c, 0x8b, 0x8e, 0xcd, 0x56, 0xb3, 0x34, 0x9a,
	0x47, 0xcb, 0x31, 0x89, 0xfb, 0x2e, 0x3b, 0xb5, 0xf7, 0x3b, 0x90, 0xc2, 0x30, 0xa9, 0xcd, 0xf6,
	0xcd, 0xe9, 0xf1, 0x2b, 0x9a, 0xac, 0x01, 0x9a, 0x2f, 0xa1, 0xa8, 0x61, 0x6d, 0x7a, 0x32, 0x3f,
	0x5a, 0x4e, 0x1e, 0x2e, 0xf2, 0xc3, 0x1e, 0x79, 0xa1, 0x78, 0x41, 0x0d, 0xb9, 0xe9, 0xbb, 0x2c,
	0x09, 0xc8, 0xc0, 0x28, 0x34, 0x58, 0x54, 0x28, 0xf1, 0x5b, 0x3c, 0x7b, 0x21, 0x7e, 0x41, 0xa3,
	0x3f, 0x5a, 0x6f, 0x58, 0x9b, 0x46, 0x2e, 0x63, 0x16, 0x64, 0x94, 0xf6, 0x1f, 0x01, 0x4c, 0x2e,
	0xfb, 0x2e, 0x3b, 0x1f, 0xf0, 0x20, 0x68, 0x6f, 0x40, 0x3e, 0xd1, 0x15, 0x34, 0xdc, 0xcd, 0xd7,
	0x54, 0x71, 0x6f, 0x44, 0xce, 0x7c, 0x76, 0x69, 0x5b, 0x29, 0xa3, 0x0f, 0xcc, 0x85, 0xf9, 0xde,
	0x54, 0xf9, 0x1a, 0x24, 0xb6, 0xe0, 0xbd, 0x1d, 0x19, 0xea, 0xe3, 0x80, 0xf5, 0x2f, 0xc7, 0x87,
	0x3e, 0x9f, 0xec, 0x51, 0x8d, 0x5c, 0x9f, 0x8f, 0xbb, 0x00, 0x00, 0x00, 0xff, 0xff, 0x06, 0xa6,
	0xff, 0x2e, 0xa9, 0x01, 0x00, 0x00,
}
