// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mojo/geom/polygon.proto

package geom

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mojo-lang/core/go/pkg/mojo"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Polygon struct {
	Type                 string        `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	LineStrings          []*LineString `protobuf:"bytes,5,rep,name=line_strings,json=lineStrings,proto3" json:"coordinates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-" gorm:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte        `json:"-" gorm:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32         `json:"-" gorm:"-" xml:"-" bson:"-"`
}

func (m *Polygon) Reset()         { *m = Polygon{} }
func (m *Polygon) String() string { return proto.CompactTextString(m) }
func (*Polygon) ProtoMessage()    {}
func (*Polygon) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d68db60d9be16c7, []int{0}
}
func (m *Polygon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Polygon.Unmarshal(m, b)
}
func (m *Polygon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Polygon.Marshal(b, m, deterministic)
}
func (m *Polygon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Polygon.Merge(m, src)
}
func (m *Polygon) XXX_Size() int {
	return xxx_messageInfo_Polygon.Size(m)
}
func (m *Polygon) XXX_DiscardUnknown() {
	xxx_messageInfo_Polygon.DiscardUnknown(m)
}

var xxx_messageInfo_Polygon proto.InternalMessageInfo

func (m *Polygon) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Polygon) GetLineStrings() []*LineString {
	if m != nil {
		return m.LineStrings
	}
	return nil
}

type LinearRingCoordinates struct {
	Vals                 []*PointCoordinates `protobuf:"bytes,1,rep,name=vals,proto3" json:"vals,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-" gorm:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte              `json:"-" gorm:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32               `json:"-" gorm:"-" xml:"-" bson:"-"`
}

func (m *LinearRingCoordinates) Reset()         { *m = LinearRingCoordinates{} }
func (m *LinearRingCoordinates) String() string { return proto.CompactTextString(m) }
func (*LinearRingCoordinates) ProtoMessage()    {}
func (*LinearRingCoordinates) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d68db60d9be16c7, []int{1}
}
func (m *LinearRingCoordinates) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LinearRingCoordinates.Unmarshal(m, b)
}
func (m *LinearRingCoordinates) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LinearRingCoordinates.Marshal(b, m, deterministic)
}
func (m *LinearRingCoordinates) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LinearRingCoordinates.Merge(m, src)
}
func (m *LinearRingCoordinates) XXX_Size() int {
	return xxx_messageInfo_LinearRingCoordinates.Size(m)
}
func (m *LinearRingCoordinates) XXX_DiscardUnknown() {
	xxx_messageInfo_LinearRingCoordinates.DiscardUnknown(m)
}

var xxx_messageInfo_LinearRingCoordinates proto.InternalMessageInfo

func (m *LinearRingCoordinates) GetVals() []*PointCoordinates {
	if m != nil {
		return m.Vals
	}
	return nil
}

type PolygonCoordinates struct {
	Vals                 []*LinearRingCoordinates `protobuf:"bytes,1,rep,name=vals,proto3" json:"vals,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-" gorm:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte                   `json:"-" gorm:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32                    `json:"-" gorm:"-" xml:"-" bson:"-"`
}

func (m *PolygonCoordinates) Reset()         { *m = PolygonCoordinates{} }
func (m *PolygonCoordinates) String() string { return proto.CompactTextString(m) }
func (*PolygonCoordinates) ProtoMessage()    {}
func (*PolygonCoordinates) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d68db60d9be16c7, []int{2}
}
func (m *PolygonCoordinates) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PolygonCoordinates.Unmarshal(m, b)
}
func (m *PolygonCoordinates) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PolygonCoordinates.Marshal(b, m, deterministic)
}
func (m *PolygonCoordinates) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PolygonCoordinates.Merge(m, src)
}
func (m *PolygonCoordinates) XXX_Size() int {
	return xxx_messageInfo_PolygonCoordinates.Size(m)
}
func (m *PolygonCoordinates) XXX_DiscardUnknown() {
	xxx_messageInfo_PolygonCoordinates.DiscardUnknown(m)
}

var xxx_messageInfo_PolygonCoordinates proto.InternalMessageInfo

func (m *PolygonCoordinates) GetVals() []*LinearRingCoordinates {
	if m != nil {
		return m.Vals
	}
	return nil
}

func init() {
	proto.RegisterType((*Polygon)(nil), "mojo.geom.Polygon")
	proto.RegisterType((*LinearRingCoordinates)(nil), "mojo.geom.LinearRingCoordinates")
	proto.RegisterType((*PolygonCoordinates)(nil), "mojo.geom.PolygonCoordinates")
}

func init() { proto.RegisterFile("mojo/geom/polygon.proto", fileDescriptor_6d68db60d9be16c7) }

var fileDescriptor_6d68db60d9be16c7 = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xcf, 0x4a, 0xfc, 0x30,
	0x1c, 0xc4, 0x7f, 0xe5, 0xb7, 0x2a, 0x9b, 0x2e, 0x0a, 0x81, 0x6a, 0xd9, 0x05, 0xb7, 0x14, 0x91,
	0x1e, 0xb4, 0x05, 0x3d, 0x7a, 0xeb, 0x5e, 0x3c, 0x78, 0x28, 0xf5, 0x26, 0xfe, 0xa1, 0x5d, 0x43,
	0x8c, 0xb6, 0xf9, 0x96, 0x26, 0x0a, 0x7d, 0x10, 0xc1, 0x67, 0xf2, 0xe2, 0x1b, 0xec, 0xc5, 0xdb,
	0x3e, 0x85, 0x24, 0x2d, 0x6d, 0x54, 0xbc, 0x14, 0x92, 0x99, 0x7e, 0x26, 0xc3, 0xa0, 0xbd, 0x12,
	0x1e, 0x21, 0xa2, 0x04, 0xca, 0xa8, 0x82, 0xa2, 0xa1, 0xc0, 0xc3, 0xaa, 0x06, 0x09, 0x78, 0xac,
	0x84, 0x50, 0x09, 0xd3, 0xd9, 0xe0, 0x29, 0x18, 0x27, 0x77, 0x42, 0xd6, 0x8c, 0xd3, 0xd6, 0x37,
	0x75, 0x4c, 0x00, 0xe3, 0xb2, 0xbb, 0xde, 0xd1, 0xd7, 0x9a, 0xa1, 0x2f, 0xfc, 0x57, 0x0b, 0x6d,
	0x25, 0x6d, 0x02, 0x3e, 0x44, 0x23, 0xd9, 0x54, 0xc4, 0xb5, 0x3c, 0x2b, 0x18, 0xc7, 0x78, 0xbd,
	0x9a, 0x6f, 0xab, 0xf3, 0x11, 0x94, 0x4c, 0x92, 0xb2, 0x92, 0x4d, 0xaa, 0x75, 0x9c, 0xa3, 0x89,
	0x11, 0x28, 0xdc, 0x0d, 0xef, 0x7f, 0x60, 0x9f, 0x38, 0x61, 0xff, 0xb4, 0xf0, 0x82, 0x71, 0x72,
	0xa9, 0xd5, 0x38, 0x58, 0xaf, 0xe6, 0xce, 0x12, 0xa0, 0xbe, 0x67, 0x3c, 0x93, 0x44, 0x0c, 0xb4,
	0xf7, 0x8f, 0x03, 0xdb, 0x10, 0x52, 0xbb, 0xe8, 0xff, 0x12, 0xfe, 0x35, 0x72, 0x14, 0x24, 0xab,
	0x53, 0xc6, 0xe9, 0x62, 0x70, 0xe1, 0x05, 0x1a, 0xbd, 0x64, 0x85, 0x70, 0x2d, 0x1d, 0x3a, 0x33,
	0x42, 0x13, 0xd5, 0xd3, 0xb0, 0xb6, 0x0d, 0x94, 0xd9, 0x6c, 0xa0, 0xce, 0xfe, 0x2d, 0xc2, 0x5d,
	0x69, 0x13, 0x7d, 0xfe, 0x0d, 0xed, 0xfd, 0xe8, 0xf3, 0xeb, 0x29, 0x7f, 0xf3, 0xe3, 0x9b, 0xb7,
	0xcf, 0xfd, 0x7f, 0x68, 0x17, 0x6a, 0xaa, 0x21, 0x45, 0xc6, 0xe9, 0x40, 0x8b, 0x27, 0x5d, 0x76,
	0xa2, 0x16, 0x48, 0xac, 0xab, 0x88, 0x32, 0xf9, 0xf0, 0x9c, 0x87, 0x4b, 0x28, 0xf5, 0x34, 0xc7,
	0xca, 0xdf, 0x6e, 0x47, 0x21, 0xaa, 0x9e, 0x68, 0xd4, 0x8f, 0x79, 0xa6, 0x3e, 0xf9, 0xa6, 0xde,
	0xee, 0xf4, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xfe, 0x0d, 0xeb, 0xaa, 0x26, 0x02, 0x00, 0x00,
}
