// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/geom/bin_lng_lat.proto

// Protobuf Java Version: 3.25.1
package org.mojolang.mojo.geom;

public interface BinLngLatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mojo.geom.BinLngLat)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 longitude = 1;</code>
   * @return The longitude.
   */
  int getLongitude();

  /**
   * <code>int32 latitude = 2;</code>
   * @return The latitude.
   */
  int getLatitude();

  /**
   * <code>int32 altitude = 3;</code>
   * @return The altitude.
   */
  int getAltitude();
}
