// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/geom/bounding_box.proto

package org.mojolang.mojo.geom;

/**
 * Protobuf type {@code mojo.geom.BoundingBox}
 */
public final class BoundingBox extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:mojo.geom.BoundingBox)
    BoundingBoxOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BoundingBox.newBuilder() to construct.
  private BoundingBox(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BoundingBox() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BoundingBox();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BoundingBox(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            org.mojolang.mojo.geom.LngLat.Builder subBuilder = null;
            if (leftBottom_ != null) {
              subBuilder = leftBottom_.toBuilder();
            }
            leftBottom_ = input.readMessage(org.mojolang.mojo.geom.LngLat.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(leftBottom_);
              leftBottom_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            org.mojolang.mojo.geom.LngLat.Builder subBuilder = null;
            if (rightTop_ != null) {
              subBuilder = rightTop_.toBuilder();
            }
            rightTop_ = input.readMessage(org.mojolang.mojo.geom.LngLat.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(rightTop_);
              rightTop_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.mojolang.mojo.geom.BoundingBoxProto.internal_static_mojo_geom_BoundingBox_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.mojolang.mojo.geom.BoundingBoxProto.internal_static_mojo_geom_BoundingBox_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.mojolang.mojo.geom.BoundingBox.class, org.mojolang.mojo.geom.BoundingBox.Builder.class);
  }

  public static final int LEFT_BOTTOM_FIELD_NUMBER = 1;
  private org.mojolang.mojo.geom.LngLat leftBottom_;
  /**
   * <code>.mojo.geom.LngLat left_bottom = 1;</code>
   * @return Whether the leftBottom field is set.
   */
  @java.lang.Override
  public boolean hasLeftBottom() {
    return leftBottom_ != null;
  }
  /**
   * <code>.mojo.geom.LngLat left_bottom = 1;</code>
   * @return The leftBottom.
   */
  @java.lang.Override
  public org.mojolang.mojo.geom.LngLat getLeftBottom() {
    return leftBottom_ == null ? org.mojolang.mojo.geom.LngLat.getDefaultInstance() : leftBottom_;
  }
  /**
   * <code>.mojo.geom.LngLat left_bottom = 1;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.geom.LngLatOrBuilder getLeftBottomOrBuilder() {
    return getLeftBottom();
  }

  public static final int RIGHT_TOP_FIELD_NUMBER = 2;
  private org.mojolang.mojo.geom.LngLat rightTop_;
  /**
   * <code>.mojo.geom.LngLat right_top = 2;</code>
   * @return Whether the rightTop field is set.
   */
  @java.lang.Override
  public boolean hasRightTop() {
    return rightTop_ != null;
  }
  /**
   * <code>.mojo.geom.LngLat right_top = 2;</code>
   * @return The rightTop.
   */
  @java.lang.Override
  public org.mojolang.mojo.geom.LngLat getRightTop() {
    return rightTop_ == null ? org.mojolang.mojo.geom.LngLat.getDefaultInstance() : rightTop_;
  }
  /**
   * <code>.mojo.geom.LngLat right_top = 2;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.geom.LngLatOrBuilder getRightTopOrBuilder() {
    return getRightTop();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (leftBottom_ != null) {
      output.writeMessage(1, getLeftBottom());
    }
    if (rightTop_ != null) {
      output.writeMessage(2, getRightTop());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (leftBottom_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getLeftBottom());
    }
    if (rightTop_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getRightTop());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.mojolang.mojo.geom.BoundingBox)) {
      return super.equals(obj);
    }
    org.mojolang.mojo.geom.BoundingBox other = (org.mojolang.mojo.geom.BoundingBox) obj;

    if (hasLeftBottom() != other.hasLeftBottom()) return false;
    if (hasLeftBottom()) {
      if (!getLeftBottom()
          .equals(other.getLeftBottom())) return false;
    }
    if (hasRightTop() != other.hasRightTop()) return false;
    if (hasRightTop()) {
      if (!getRightTop()
          .equals(other.getRightTop())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasLeftBottom()) {
      hash = (37 * hash) + LEFT_BOTTOM_FIELD_NUMBER;
      hash = (53 * hash) + getLeftBottom().hashCode();
    }
    if (hasRightTop()) {
      hash = (37 * hash) + RIGHT_TOP_FIELD_NUMBER;
      hash = (53 * hash) + getRightTop().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.mojolang.mojo.geom.BoundingBox parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojolang.mojo.geom.BoundingBox parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojolang.mojo.geom.BoundingBox parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojolang.mojo.geom.BoundingBox parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojolang.mojo.geom.BoundingBox parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojolang.mojo.geom.BoundingBox parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojolang.mojo.geom.BoundingBox parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mojolang.mojo.geom.BoundingBox parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mojolang.mojo.geom.BoundingBox parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.mojolang.mojo.geom.BoundingBox parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mojolang.mojo.geom.BoundingBox parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mojolang.mojo.geom.BoundingBox parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.mojolang.mojo.geom.BoundingBox prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code mojo.geom.BoundingBox}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mojo.geom.BoundingBox)
      org.mojolang.mojo.geom.BoundingBoxOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.mojolang.mojo.geom.BoundingBoxProto.internal_static_mojo_geom_BoundingBox_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.mojolang.mojo.geom.BoundingBoxProto.internal_static_mojo_geom_BoundingBox_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.mojolang.mojo.geom.BoundingBox.class, org.mojolang.mojo.geom.BoundingBox.Builder.class);
    }

    // Construct using org.mojolang.mojo.geom.BoundingBox.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (leftBottomBuilder_ == null) {
        leftBottom_ = null;
      } else {
        leftBottom_ = null;
        leftBottomBuilder_ = null;
      }
      if (rightTopBuilder_ == null) {
        rightTop_ = null;
      } else {
        rightTop_ = null;
        rightTopBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.mojolang.mojo.geom.BoundingBoxProto.internal_static_mojo_geom_BoundingBox_descriptor;
    }

    @java.lang.Override
    public org.mojolang.mojo.geom.BoundingBox getDefaultInstanceForType() {
      return org.mojolang.mojo.geom.BoundingBox.getDefaultInstance();
    }

    @java.lang.Override
    public org.mojolang.mojo.geom.BoundingBox build() {
      org.mojolang.mojo.geom.BoundingBox result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.mojolang.mojo.geom.BoundingBox buildPartial() {
      org.mojolang.mojo.geom.BoundingBox result = new org.mojolang.mojo.geom.BoundingBox(this);
      if (leftBottomBuilder_ == null) {
        result.leftBottom_ = leftBottom_;
      } else {
        result.leftBottom_ = leftBottomBuilder_.build();
      }
      if (rightTopBuilder_ == null) {
        result.rightTop_ = rightTop_;
      } else {
        result.rightTop_ = rightTopBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.mojolang.mojo.geom.BoundingBox) {
        return mergeFrom((org.mojolang.mojo.geom.BoundingBox)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.mojolang.mojo.geom.BoundingBox other) {
      if (other == org.mojolang.mojo.geom.BoundingBox.getDefaultInstance()) return this;
      if (other.hasLeftBottom()) {
        mergeLeftBottom(other.getLeftBottom());
      }
      if (other.hasRightTop()) {
        mergeRightTop(other.getRightTop());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.mojolang.mojo.geom.BoundingBox parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.mojolang.mojo.geom.BoundingBox) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private org.mojolang.mojo.geom.LngLat leftBottom_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.geom.LngLat, org.mojolang.mojo.geom.LngLat.Builder, org.mojolang.mojo.geom.LngLatOrBuilder> leftBottomBuilder_;
    /**
     * <code>.mojo.geom.LngLat left_bottom = 1;</code>
     * @return Whether the leftBottom field is set.
     */
    public boolean hasLeftBottom() {
      return leftBottomBuilder_ != null || leftBottom_ != null;
    }
    /**
     * <code>.mojo.geom.LngLat left_bottom = 1;</code>
     * @return The leftBottom.
     */
    public org.mojolang.mojo.geom.LngLat getLeftBottom() {
      if (leftBottomBuilder_ == null) {
        return leftBottom_ == null ? org.mojolang.mojo.geom.LngLat.getDefaultInstance() : leftBottom_;
      } else {
        return leftBottomBuilder_.getMessage();
      }
    }
    /**
     * <code>.mojo.geom.LngLat left_bottom = 1;</code>
     */
    public Builder setLeftBottom(org.mojolang.mojo.geom.LngLat value) {
      if (leftBottomBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        leftBottom_ = value;
        onChanged();
      } else {
        leftBottomBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.mojo.geom.LngLat left_bottom = 1;</code>
     */
    public Builder setLeftBottom(
        org.mojolang.mojo.geom.LngLat.Builder builderForValue) {
      if (leftBottomBuilder_ == null) {
        leftBottom_ = builderForValue.build();
        onChanged();
      } else {
        leftBottomBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.mojo.geom.LngLat left_bottom = 1;</code>
     */
    public Builder mergeLeftBottom(org.mojolang.mojo.geom.LngLat value) {
      if (leftBottomBuilder_ == null) {
        if (leftBottom_ != null) {
          leftBottom_ =
            org.mojolang.mojo.geom.LngLat.newBuilder(leftBottom_).mergeFrom(value).buildPartial();
        } else {
          leftBottom_ = value;
        }
        onChanged();
      } else {
        leftBottomBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.mojo.geom.LngLat left_bottom = 1;</code>
     */
    public Builder clearLeftBottom() {
      if (leftBottomBuilder_ == null) {
        leftBottom_ = null;
        onChanged();
      } else {
        leftBottom_ = null;
        leftBottomBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.mojo.geom.LngLat left_bottom = 1;</code>
     */
    public org.mojolang.mojo.geom.LngLat.Builder getLeftBottomBuilder() {
      
      onChanged();
      return getLeftBottomFieldBuilder().getBuilder();
    }
    /**
     * <code>.mojo.geom.LngLat left_bottom = 1;</code>
     */
    public org.mojolang.mojo.geom.LngLatOrBuilder getLeftBottomOrBuilder() {
      if (leftBottomBuilder_ != null) {
        return leftBottomBuilder_.getMessageOrBuilder();
      } else {
        return leftBottom_ == null ?
            org.mojolang.mojo.geom.LngLat.getDefaultInstance() : leftBottom_;
      }
    }
    /**
     * <code>.mojo.geom.LngLat left_bottom = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.geom.LngLat, org.mojolang.mojo.geom.LngLat.Builder, org.mojolang.mojo.geom.LngLatOrBuilder> 
        getLeftBottomFieldBuilder() {
      if (leftBottomBuilder_ == null) {
        leftBottomBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.mojolang.mojo.geom.LngLat, org.mojolang.mojo.geom.LngLat.Builder, org.mojolang.mojo.geom.LngLatOrBuilder>(
                getLeftBottom(),
                getParentForChildren(),
                isClean());
        leftBottom_ = null;
      }
      return leftBottomBuilder_;
    }

    private org.mojolang.mojo.geom.LngLat rightTop_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.geom.LngLat, org.mojolang.mojo.geom.LngLat.Builder, org.mojolang.mojo.geom.LngLatOrBuilder> rightTopBuilder_;
    /**
     * <code>.mojo.geom.LngLat right_top = 2;</code>
     * @return Whether the rightTop field is set.
     */
    public boolean hasRightTop() {
      return rightTopBuilder_ != null || rightTop_ != null;
    }
    /**
     * <code>.mojo.geom.LngLat right_top = 2;</code>
     * @return The rightTop.
     */
    public org.mojolang.mojo.geom.LngLat getRightTop() {
      if (rightTopBuilder_ == null) {
        return rightTop_ == null ? org.mojolang.mojo.geom.LngLat.getDefaultInstance() : rightTop_;
      } else {
        return rightTopBuilder_.getMessage();
      }
    }
    /**
     * <code>.mojo.geom.LngLat right_top = 2;</code>
     */
    public Builder setRightTop(org.mojolang.mojo.geom.LngLat value) {
      if (rightTopBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        rightTop_ = value;
        onChanged();
      } else {
        rightTopBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.mojo.geom.LngLat right_top = 2;</code>
     */
    public Builder setRightTop(
        org.mojolang.mojo.geom.LngLat.Builder builderForValue) {
      if (rightTopBuilder_ == null) {
        rightTop_ = builderForValue.build();
        onChanged();
      } else {
        rightTopBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.mojo.geom.LngLat right_top = 2;</code>
     */
    public Builder mergeRightTop(org.mojolang.mojo.geom.LngLat value) {
      if (rightTopBuilder_ == null) {
        if (rightTop_ != null) {
          rightTop_ =
            org.mojolang.mojo.geom.LngLat.newBuilder(rightTop_).mergeFrom(value).buildPartial();
        } else {
          rightTop_ = value;
        }
        onChanged();
      } else {
        rightTopBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.mojo.geom.LngLat right_top = 2;</code>
     */
    public Builder clearRightTop() {
      if (rightTopBuilder_ == null) {
        rightTop_ = null;
        onChanged();
      } else {
        rightTop_ = null;
        rightTopBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.mojo.geom.LngLat right_top = 2;</code>
     */
    public org.mojolang.mojo.geom.LngLat.Builder getRightTopBuilder() {
      
      onChanged();
      return getRightTopFieldBuilder().getBuilder();
    }
    /**
     * <code>.mojo.geom.LngLat right_top = 2;</code>
     */
    public org.mojolang.mojo.geom.LngLatOrBuilder getRightTopOrBuilder() {
      if (rightTopBuilder_ != null) {
        return rightTopBuilder_.getMessageOrBuilder();
      } else {
        return rightTop_ == null ?
            org.mojolang.mojo.geom.LngLat.getDefaultInstance() : rightTop_;
      }
    }
    /**
     * <code>.mojo.geom.LngLat right_top = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.geom.LngLat, org.mojolang.mojo.geom.LngLat.Builder, org.mojolang.mojo.geom.LngLatOrBuilder> 
        getRightTopFieldBuilder() {
      if (rightTopBuilder_ == null) {
        rightTopBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.mojolang.mojo.geom.LngLat, org.mojolang.mojo.geom.LngLat.Builder, org.mojolang.mojo.geom.LngLatOrBuilder>(
                getRightTop(),
                getParentForChildren(),
                isClean());
        rightTop_ = null;
      }
      return rightTopBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:mojo.geom.BoundingBox)
  }

  // @@protoc_insertion_point(class_scope:mojo.geom.BoundingBox)
  private static final org.mojolang.mojo.geom.BoundingBox DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.mojolang.mojo.geom.BoundingBox();
  }

  public static org.mojolang.mojo.geom.BoundingBox getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BoundingBox>
      PARSER = new com.google.protobuf.AbstractParser<BoundingBox>() {
    @java.lang.Override
    public BoundingBox parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BoundingBox(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BoundingBox> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BoundingBox> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.mojolang.mojo.geom.BoundingBox getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

