// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/geom/circle.proto

package org.mojolang.mojo.geom;

public final class CircleProto {
  private CircleProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_geom_Circle_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_geom_Circle_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026mojo/geom/circle.proto\022\tmojo.geom\032\027moj" +
      "o/geom/lng_lat.proto\032\017mojo/mojo.proto\"Z\n" +
      "\006Circle\022\014\n\004type\030\001 \001(\t\0222\n\006center\030\002 \001(\0132\021." +
      "mojo.geom.LngLatB\017\312\317$\013coordinates\022\016\n\006rad" +
      "ius\030\005 \001(\002BX\n\026org.mojolang.mojo.geomB\013Cir" +
      "cleProtoP\001Z/github.com/mojo-lang/geom/go" +
      "/pkg/mojo/geom;geomb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.mojolang.mojo.geom.LngLatProto.getDescriptor(),
          org.mojolang.mojo.MojoProtos.getDescriptor(),
        });
    internal_static_mojo_geom_Circle_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mojo_geom_Circle_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_geom_Circle_descriptor,
        new java.lang.String[] { "Type", "Center", "Radius", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(org.mojolang.mojo.MojoProtos.alias);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    org.mojolang.mojo.geom.LngLatProto.getDescriptor();
    org.mojolang.mojo.MojoProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
