// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/geom/circle.proto

package org.mojolang.mojo.geom;

/**
 * Protobuf type {@code mojo.geom.Circle}
 */
public final class Circle extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:mojo.geom.Circle)
    CircleOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Circle.newBuilder() to construct.
  private Circle(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Circle() {
    type_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Circle();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Circle(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            type_ = s;
            break;
          }
          case 18: {
            org.mojolang.mojo.geom.LngLat.Builder subBuilder = null;
            if (coordinate_ != null) {
              subBuilder = coordinate_.toBuilder();
            }
            coordinate_ = input.readMessage(org.mojolang.mojo.geom.LngLat.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(coordinate_);
              coordinate_ = subBuilder.buildPartial();
            }

            break;
          }
          case 45: {

            radius_ = input.readFloat();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.mojolang.mojo.geom.CircleProto.internal_static_mojo_geom_Circle_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.mojolang.mojo.geom.CircleProto.internal_static_mojo_geom_Circle_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.mojolang.mojo.geom.Circle.class, org.mojolang.mojo.geom.Circle.Builder.class);
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private volatile java.lang.Object type_;
  /**
   * <code>string type = 1;</code>
   * @return The type.
   */
  @java.lang.Override
  public java.lang.String getType() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      type_ = s;
      return s;
    }
  }
  /**
   * <code>string type = 1;</code>
   * @return The bytes for type.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTypeBytes() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      type_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COORDINATE_FIELD_NUMBER = 2;
  private org.mojolang.mojo.geom.LngLat coordinate_;
  /**
   * <code>.mojo.geom.LngLat coordinate = 2 [(.mojo.alias) = "coordinates"];</code>
   * @return Whether the coordinate field is set.
   */
  @java.lang.Override
  public boolean hasCoordinate() {
    return coordinate_ != null;
  }
  /**
   * <code>.mojo.geom.LngLat coordinate = 2 [(.mojo.alias) = "coordinates"];</code>
   * @return The coordinate.
   */
  @java.lang.Override
  public org.mojolang.mojo.geom.LngLat getCoordinate() {
    return coordinate_ == null ? org.mojolang.mojo.geom.LngLat.getDefaultInstance() : coordinate_;
  }
  /**
   * <code>.mojo.geom.LngLat coordinate = 2 [(.mojo.alias) = "coordinates"];</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.geom.LngLatOrBuilder getCoordinateOrBuilder() {
    return getCoordinate();
  }

  public static final int RADIUS_FIELD_NUMBER = 5;
  private float radius_;
  /**
   * <code>float radius = 5;</code>
   * @return The radius.
   */
  @java.lang.Override
  public float getRadius() {
    return radius_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, type_);
    }
    if (coordinate_ != null) {
      output.writeMessage(2, getCoordinate());
    }
    if (radius_ != 0F) {
      output.writeFloat(5, radius_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, type_);
    }
    if (coordinate_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getCoordinate());
    }
    if (radius_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(5, radius_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.mojolang.mojo.geom.Circle)) {
      return super.equals(obj);
    }
    org.mojolang.mojo.geom.Circle other = (org.mojolang.mojo.geom.Circle) obj;

    if (!getType()
        .equals(other.getType())) return false;
    if (hasCoordinate() != other.hasCoordinate()) return false;
    if (hasCoordinate()) {
      if (!getCoordinate()
          .equals(other.getCoordinate())) return false;
    }
    if (java.lang.Float.floatToIntBits(getRadius())
        != java.lang.Float.floatToIntBits(
            other.getRadius())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType().hashCode();
    if (hasCoordinate()) {
      hash = (37 * hash) + COORDINATE_FIELD_NUMBER;
      hash = (53 * hash) + getCoordinate().hashCode();
    }
    hash = (37 * hash) + RADIUS_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getRadius());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.mojolang.mojo.geom.Circle parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojolang.mojo.geom.Circle parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojolang.mojo.geom.Circle parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojolang.mojo.geom.Circle parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojolang.mojo.geom.Circle parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojolang.mojo.geom.Circle parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojolang.mojo.geom.Circle parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mojolang.mojo.geom.Circle parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mojolang.mojo.geom.Circle parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.mojolang.mojo.geom.Circle parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mojolang.mojo.geom.Circle parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mojolang.mojo.geom.Circle parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.mojolang.mojo.geom.Circle prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code mojo.geom.Circle}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mojo.geom.Circle)
      org.mojolang.mojo.geom.CircleOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.mojolang.mojo.geom.CircleProto.internal_static_mojo_geom_Circle_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.mojolang.mojo.geom.CircleProto.internal_static_mojo_geom_Circle_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.mojolang.mojo.geom.Circle.class, org.mojolang.mojo.geom.Circle.Builder.class);
    }

    // Construct using org.mojolang.mojo.geom.Circle.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      type_ = "";

      if (coordinateBuilder_ == null) {
        coordinate_ = null;
      } else {
        coordinate_ = null;
        coordinateBuilder_ = null;
      }
      radius_ = 0F;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.mojolang.mojo.geom.CircleProto.internal_static_mojo_geom_Circle_descriptor;
    }

    @java.lang.Override
    public org.mojolang.mojo.geom.Circle getDefaultInstanceForType() {
      return org.mojolang.mojo.geom.Circle.getDefaultInstance();
    }

    @java.lang.Override
    public org.mojolang.mojo.geom.Circle build() {
      org.mojolang.mojo.geom.Circle result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.mojolang.mojo.geom.Circle buildPartial() {
      org.mojolang.mojo.geom.Circle result = new org.mojolang.mojo.geom.Circle(this);
      result.type_ = type_;
      if (coordinateBuilder_ == null) {
        result.coordinate_ = coordinate_;
      } else {
        result.coordinate_ = coordinateBuilder_.build();
      }
      result.radius_ = radius_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.mojolang.mojo.geom.Circle) {
        return mergeFrom((org.mojolang.mojo.geom.Circle)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.mojolang.mojo.geom.Circle other) {
      if (other == org.mojolang.mojo.geom.Circle.getDefaultInstance()) return this;
      if (!other.getType().isEmpty()) {
        type_ = other.type_;
        onChanged();
      }
      if (other.hasCoordinate()) {
        mergeCoordinate(other.getCoordinate());
      }
      if (other.getRadius() != 0F) {
        setRadius(other.getRadius());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.mojolang.mojo.geom.Circle parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.mojolang.mojo.geom.Circle) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object type_ = "";
    /**
     * <code>string type = 1;</code>
     * @return The type.
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string type = 1;</code>
     * @return The bytes for type.
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string type = 1;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      
      type_ = getDefaultInstance().getType();
      onChanged();
      return this;
    }
    /**
     * <code>string type = 1;</code>
     * @param value The bytes for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      type_ = value;
      onChanged();
      return this;
    }

    private org.mojolang.mojo.geom.LngLat coordinate_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.geom.LngLat, org.mojolang.mojo.geom.LngLat.Builder, org.mojolang.mojo.geom.LngLatOrBuilder> coordinateBuilder_;
    /**
     * <code>.mojo.geom.LngLat coordinate = 2 [(.mojo.alias) = "coordinates"];</code>
     * @return Whether the coordinate field is set.
     */
    public boolean hasCoordinate() {
      return coordinateBuilder_ != null || coordinate_ != null;
    }
    /**
     * <code>.mojo.geom.LngLat coordinate = 2 [(.mojo.alias) = "coordinates"];</code>
     * @return The coordinate.
     */
    public org.mojolang.mojo.geom.LngLat getCoordinate() {
      if (coordinateBuilder_ == null) {
        return coordinate_ == null ? org.mojolang.mojo.geom.LngLat.getDefaultInstance() : coordinate_;
      } else {
        return coordinateBuilder_.getMessage();
      }
    }
    /**
     * <code>.mojo.geom.LngLat coordinate = 2 [(.mojo.alias) = "coordinates"];</code>
     */
    public Builder setCoordinate(org.mojolang.mojo.geom.LngLat value) {
      if (coordinateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        coordinate_ = value;
        onChanged();
      } else {
        coordinateBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.mojo.geom.LngLat coordinate = 2 [(.mojo.alias) = "coordinates"];</code>
     */
    public Builder setCoordinate(
        org.mojolang.mojo.geom.LngLat.Builder builderForValue) {
      if (coordinateBuilder_ == null) {
        coordinate_ = builderForValue.build();
        onChanged();
      } else {
        coordinateBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.mojo.geom.LngLat coordinate = 2 [(.mojo.alias) = "coordinates"];</code>
     */
    public Builder mergeCoordinate(org.mojolang.mojo.geom.LngLat value) {
      if (coordinateBuilder_ == null) {
        if (coordinate_ != null) {
          coordinate_ =
            org.mojolang.mojo.geom.LngLat.newBuilder(coordinate_).mergeFrom(value).buildPartial();
        } else {
          coordinate_ = value;
        }
        onChanged();
      } else {
        coordinateBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.mojo.geom.LngLat coordinate = 2 [(.mojo.alias) = "coordinates"];</code>
     */
    public Builder clearCoordinate() {
      if (coordinateBuilder_ == null) {
        coordinate_ = null;
        onChanged();
      } else {
        coordinate_ = null;
        coordinateBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.mojo.geom.LngLat coordinate = 2 [(.mojo.alias) = "coordinates"];</code>
     */
    public org.mojolang.mojo.geom.LngLat.Builder getCoordinateBuilder() {
      
      onChanged();
      return getCoordinateFieldBuilder().getBuilder();
    }
    /**
     * <code>.mojo.geom.LngLat coordinate = 2 [(.mojo.alias) = "coordinates"];</code>
     */
    public org.mojolang.mojo.geom.LngLatOrBuilder getCoordinateOrBuilder() {
      if (coordinateBuilder_ != null) {
        return coordinateBuilder_.getMessageOrBuilder();
      } else {
        return coordinate_ == null ?
            org.mojolang.mojo.geom.LngLat.getDefaultInstance() : coordinate_;
      }
    }
    /**
     * <code>.mojo.geom.LngLat coordinate = 2 [(.mojo.alias) = "coordinates"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.geom.LngLat, org.mojolang.mojo.geom.LngLat.Builder, org.mojolang.mojo.geom.LngLatOrBuilder> 
        getCoordinateFieldBuilder() {
      if (coordinateBuilder_ == null) {
        coordinateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.mojolang.mojo.geom.LngLat, org.mojolang.mojo.geom.LngLat.Builder, org.mojolang.mojo.geom.LngLatOrBuilder>(
                getCoordinate(),
                getParentForChildren(),
                isClean());
        coordinate_ = null;
      }
      return coordinateBuilder_;
    }

    private float radius_ ;
    /**
     * <code>float radius = 5;</code>
     * @return The radius.
     */
    @java.lang.Override
    public float getRadius() {
      return radius_;
    }
    /**
     * <code>float radius = 5;</code>
     * @param value The radius to set.
     * @return This builder for chaining.
     */
    public Builder setRadius(float value) {
      
      radius_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float radius = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearRadius() {
      
      radius_ = 0F;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:mojo.geom.Circle)
  }

  // @@protoc_insertion_point(class_scope:mojo.geom.Circle)
  private static final org.mojolang.mojo.geom.Circle DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.mojolang.mojo.geom.Circle();
  }

  public static org.mojolang.mojo.geom.Circle getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Circle>
      PARSER = new com.google.protobuf.AbstractParser<Circle>() {
    @java.lang.Override
    public Circle parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Circle(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Circle> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Circle> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.mojolang.mojo.geom.Circle getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

