// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/geom/circle.proto

package org.mojolang.mojo.geom;

public interface CircleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mojo.geom.Circle)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string type = 1;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 1;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>.mojo.geom.LngLat coordinate = 2 [(.mojo.alias) = "coordinates"];</code>
   * @return Whether the coordinate field is set.
   */
  boolean hasCoordinate();
  /**
   * <code>.mojo.geom.LngLat coordinate = 2 [(.mojo.alias) = "coordinates"];</code>
   * @return The coordinate.
   */
  org.mojolang.mojo.geom.LngLat getCoordinate();
  /**
   * <code>.mojo.geom.LngLat coordinate = 2 [(.mojo.alias) = "coordinates"];</code>
   */
  org.mojolang.mojo.geom.LngLatOrBuilder getCoordinateOrBuilder();

  /**
   * <code>float radius = 5;</code>
   * @return The radius.
   */
  float getRadius();
}
