// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/geom/circle.proto

package org.mojolang.mojo.geom;

/**
 * Protobuf type {@code mojo.geom.Circle}
 */
public final class Circle extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:mojo.geom.Circle)
    CircleOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Circle.newBuilder() to construct.
  private Circle(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Circle() {
    type_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Circle();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.mojolang.mojo.geom.CircleProto.internal_static_mojo_geom_Circle_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.mojolang.mojo.geom.CircleProto.internal_static_mojo_geom_Circle_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.mojolang.mojo.geom.Circle.class, org.mojolang.mojo.geom.Circle.Builder.class);
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object type_ = "";
  /**
   * <code>string type = 1;</code>
   * @return The type.
   */
  @java.lang.Override
  public java.lang.String getType() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      type_ = s;
      return s;
    }
  }
  /**
   * <code>string type = 1;</code>
   * @return The bytes for type.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTypeBytes() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      type_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CENTER_FIELD_NUMBER = 2;
  private org.mojolang.mojo.geom.LngLat center_;
  /**
   * <code>.mojo.geom.LngLat center = 2 [(.mojo.alias) = "coordinates"];</code>
   * @return Whether the center field is set.
   */
  @java.lang.Override
  public boolean hasCenter() {
    return center_ != null;
  }
  /**
   * <code>.mojo.geom.LngLat center = 2 [(.mojo.alias) = "coordinates"];</code>
   * @return The center.
   */
  @java.lang.Override
  public org.mojolang.mojo.geom.LngLat getCenter() {
    return center_ == null ? org.mojolang.mojo.geom.LngLat.getDefaultInstance() : center_;
  }
  /**
   * <code>.mojo.geom.LngLat center = 2 [(.mojo.alias) = "coordinates"];</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.geom.LngLatOrBuilder getCenterOrBuilder() {
    return center_ == null ? org.mojolang.mojo.geom.LngLat.getDefaultInstance() : center_;
  }

  public static final int RADIUS_FIELD_NUMBER = 5;
  private float radius_ = 0F;
  /**
   * <code>float radius = 5;</code>
   * @return The radius.
   */
  @java.lang.Override
  public float getRadius() {
    return radius_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, type_);
    }
    if (center_ != null) {
      output.writeMessage(2, getCenter());
    }
    if (java.lang.Float.floatToRawIntBits(radius_) != 0) {
      output.writeFloat(5, radius_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, type_);
    }
    if (center_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getCenter());
    }
    if (java.lang.Float.floatToRawIntBits(radius_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(5, radius_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.mojolang.mojo.geom.Circle)) {
      return super.equals(obj);
    }
    org.mojolang.mojo.geom.Circle other = (org.mojolang.mojo.geom.Circle) obj;

    if (!getType()
        .equals(other.getType())) return false;
    if (hasCenter() != other.hasCenter()) return false;
    if (hasCenter()) {
      if (!getCenter()
          .equals(other.getCenter())) return false;
    }
    if (java.lang.Float.floatToIntBits(getRadius())
        != java.lang.Float.floatToIntBits(
            other.getRadius())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType().hashCode();
    if (hasCenter()) {
      hash = (37 * hash) + CENTER_FIELD_NUMBER;
      hash = (53 * hash) + getCenter().hashCode();
    }
    hash = (37 * hash) + RADIUS_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getRadius());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.mojolang.mojo.geom.Circle parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojolang.mojo.geom.Circle parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojolang.mojo.geom.Circle parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojolang.mojo.geom.Circle parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojolang.mojo.geom.Circle parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojolang.mojo.geom.Circle parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojolang.mojo.geom.Circle parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mojolang.mojo.geom.Circle parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mojolang.mojo.geom.Circle parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.mojolang.mojo.geom.Circle parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mojolang.mojo.geom.Circle parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mojolang.mojo.geom.Circle parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.mojolang.mojo.geom.Circle prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code mojo.geom.Circle}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mojo.geom.Circle)
      org.mojolang.mojo.geom.CircleOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.mojolang.mojo.geom.CircleProto.internal_static_mojo_geom_Circle_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.mojolang.mojo.geom.CircleProto.internal_static_mojo_geom_Circle_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.mojolang.mojo.geom.Circle.class, org.mojolang.mojo.geom.Circle.Builder.class);
    }

    // Construct using org.mojolang.mojo.geom.Circle.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      type_ = "";
      center_ = null;
      if (centerBuilder_ != null) {
        centerBuilder_.dispose();
        centerBuilder_ = null;
      }
      radius_ = 0F;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.mojolang.mojo.geom.CircleProto.internal_static_mojo_geom_Circle_descriptor;
    }

    @java.lang.Override
    public org.mojolang.mojo.geom.Circle getDefaultInstanceForType() {
      return org.mojolang.mojo.geom.Circle.getDefaultInstance();
    }

    @java.lang.Override
    public org.mojolang.mojo.geom.Circle build() {
      org.mojolang.mojo.geom.Circle result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.mojolang.mojo.geom.Circle buildPartial() {
      org.mojolang.mojo.geom.Circle result = new org.mojolang.mojo.geom.Circle(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.mojolang.mojo.geom.Circle result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.type_ = type_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.center_ = centerBuilder_ == null
            ? center_
            : centerBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.radius_ = radius_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.mojolang.mojo.geom.Circle) {
        return mergeFrom((org.mojolang.mojo.geom.Circle)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.mojolang.mojo.geom.Circle other) {
      if (other == org.mojolang.mojo.geom.Circle.getDefaultInstance()) return this;
      if (!other.getType().isEmpty()) {
        type_ = other.type_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasCenter()) {
        mergeCenter(other.getCenter());
      }
      if (other.getRadius() != 0F) {
        setRadius(other.getRadius());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              type_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getCenterFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 45: {
              radius_ = input.readFloat();
              bitField0_ |= 0x00000004;
              break;
            } // case 45
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object type_ = "";
    /**
     * <code>string type = 1;</code>
     * @return The type.
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string type = 1;</code>
     * @return The bytes for type.
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string type = 1;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      type_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      type_ = getDefaultInstance().getType();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string type = 1;</code>
     * @param value The bytes for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      type_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private org.mojolang.mojo.geom.LngLat center_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.geom.LngLat, org.mojolang.mojo.geom.LngLat.Builder, org.mojolang.mojo.geom.LngLatOrBuilder> centerBuilder_;
    /**
     * <code>.mojo.geom.LngLat center = 2 [(.mojo.alias) = "coordinates"];</code>
     * @return Whether the center field is set.
     */
    public boolean hasCenter() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.mojo.geom.LngLat center = 2 [(.mojo.alias) = "coordinates"];</code>
     * @return The center.
     */
    public org.mojolang.mojo.geom.LngLat getCenter() {
      if (centerBuilder_ == null) {
        return center_ == null ? org.mojolang.mojo.geom.LngLat.getDefaultInstance() : center_;
      } else {
        return centerBuilder_.getMessage();
      }
    }
    /**
     * <code>.mojo.geom.LngLat center = 2 [(.mojo.alias) = "coordinates"];</code>
     */
    public Builder setCenter(org.mojolang.mojo.geom.LngLat value) {
      if (centerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        center_ = value;
      } else {
        centerBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.geom.LngLat center = 2 [(.mojo.alias) = "coordinates"];</code>
     */
    public Builder setCenter(
        org.mojolang.mojo.geom.LngLat.Builder builderForValue) {
      if (centerBuilder_ == null) {
        center_ = builderForValue.build();
      } else {
        centerBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.geom.LngLat center = 2 [(.mojo.alias) = "coordinates"];</code>
     */
    public Builder mergeCenter(org.mojolang.mojo.geom.LngLat value) {
      if (centerBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          center_ != null &&
          center_ != org.mojolang.mojo.geom.LngLat.getDefaultInstance()) {
          getCenterBuilder().mergeFrom(value);
        } else {
          center_ = value;
        }
      } else {
        centerBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.geom.LngLat center = 2 [(.mojo.alias) = "coordinates"];</code>
     */
    public Builder clearCenter() {
      bitField0_ = (bitField0_ & ~0x00000002);
      center_ = null;
      if (centerBuilder_ != null) {
        centerBuilder_.dispose();
        centerBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.geom.LngLat center = 2 [(.mojo.alias) = "coordinates"];</code>
     */
    public org.mojolang.mojo.geom.LngLat.Builder getCenterBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getCenterFieldBuilder().getBuilder();
    }
    /**
     * <code>.mojo.geom.LngLat center = 2 [(.mojo.alias) = "coordinates"];</code>
     */
    public org.mojolang.mojo.geom.LngLatOrBuilder getCenterOrBuilder() {
      if (centerBuilder_ != null) {
        return centerBuilder_.getMessageOrBuilder();
      } else {
        return center_ == null ?
            org.mojolang.mojo.geom.LngLat.getDefaultInstance() : center_;
      }
    }
    /**
     * <code>.mojo.geom.LngLat center = 2 [(.mojo.alias) = "coordinates"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.geom.LngLat, org.mojolang.mojo.geom.LngLat.Builder, org.mojolang.mojo.geom.LngLatOrBuilder> 
        getCenterFieldBuilder() {
      if (centerBuilder_ == null) {
        centerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.mojolang.mojo.geom.LngLat, org.mojolang.mojo.geom.LngLat.Builder, org.mojolang.mojo.geom.LngLatOrBuilder>(
                getCenter(),
                getParentForChildren(),
                isClean());
        center_ = null;
      }
      return centerBuilder_;
    }

    private float radius_ ;
    /**
     * <code>float radius = 5;</code>
     * @return The radius.
     */
    @java.lang.Override
    public float getRadius() {
      return radius_;
    }
    /**
     * <code>float radius = 5;</code>
     * @param value The radius to set.
     * @return This builder for chaining.
     */
    public Builder setRadius(float value) {
      
      radius_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>float radius = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearRadius() {
      bitField0_ = (bitField0_ & ~0x00000004);
      radius_ = 0F;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:mojo.geom.Circle)
  }

  // @@protoc_insertion_point(class_scope:mojo.geom.Circle)
  private static final org.mojolang.mojo.geom.Circle DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.mojolang.mojo.geom.Circle();
  }

  public static org.mojolang.mojo.geom.Circle getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Circle>
      PARSER = new com.google.protobuf.AbstractParser<Circle>() {
    @java.lang.Override
    public Circle parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Circle> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Circle> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.mojolang.mojo.geom.Circle getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

