// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/geom/feature_collection.proto

// Protobuf Java Version: 3.25.1
package org.mojolang.mojo.geom;

public final class FeatureCollectionProto {
  private FeatureCollectionProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_geom_FeatureCollection_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_geom_FeatureCollection_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"mojo/geom/feature_collection.proto\022\tmo" +
      "jo.geom\032\025mojo/core/value.proto\032\027mojo/geo" +
      "m/feature.proto\"w\n\021FeatureCollection\022\014\n\004" +
      "type\030\001 \001(\t\022$\n\010features\030\005 \003(\0132\022.mojo.geom" +
      ".Feature\022\014\n\004keys\030\r \003(\t\022 \n\006values\030\016 \003(\0132\020" +
      ".mojo.core.ValueBc\n\026org.mojolang.mojo.ge" +
      "omB\026FeatureCollectionProtoP\001Z/github.com" +
      "/mojo-lang/geom/go/pkg/mojo/geom;geomb\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.mojolang.mojo.core.ValueProto.getDescriptor(),
          org.mojolang.mojo.geom.FeatureProto.getDescriptor(),
        });
    internal_static_mojo_geom_FeatureCollection_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mojo_geom_FeatureCollection_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_geom_FeatureCollection_descriptor,
        new java.lang.String[] { "Type", "Features", "Keys", "Values", });
    org.mojolang.mojo.core.ValueProto.getDescriptor();
    org.mojolang.mojo.geom.FeatureProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
