// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/geom/feature.proto

package org.mojolang.mojo.geom;

/**
 * Protobuf type {@code mojo.geom.Feature}
 */
public final class Feature extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:mojo.geom.Feature)
    FeatureOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Feature.newBuilder() to construct.
  private Feature(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Feature() {
    type_ = "";
    spatialReference_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Feature();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.mojolang.mojo.geom.FeatureProto.internal_static_mojo_geom_Feature_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 6:
        return internalGetProperties();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.mojolang.mojo.geom.FeatureProto.internal_static_mojo_geom_Feature_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.mojolang.mojo.geom.Feature.class, org.mojolang.mojo.geom.Feature.Builder.class);
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private volatile java.lang.Object type_;
  /**
   * <code>string type = 1;</code>
   * @return The type.
   */
  @java.lang.Override
  public java.lang.String getType() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      type_ = s;
      return s;
    }
  }
  /**
   * <code>string type = 1;</code>
   * @return The bytes for type.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTypeBytes() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      type_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ID_FIELD_NUMBER = 2;
  private org.mojolang.mojo.core.Id id_;
  /**
   * <code>.mojo.core.Id id = 2;</code>
   * @return Whether the id field is set.
   */
  @java.lang.Override
  public boolean hasId() {
    return id_ != null;
  }
  /**
   * <code>.mojo.core.Id id = 2;</code>
   * @return The id.
   */
  @java.lang.Override
  public org.mojolang.mojo.core.Id getId() {
    return id_ == null ? org.mojolang.mojo.core.Id.getDefaultInstance() : id_;
  }
  /**
   * <code>.mojo.core.Id id = 2;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.core.IdOrBuilder getIdOrBuilder() {
    return getId();
  }

  public static final int GEOMETRY_FIELD_NUMBER = 3;
  private org.mojolang.mojo.geom.Geometry geometry_;
  /**
   * <code>.mojo.geom.Geometry geometry = 3;</code>
   * @return Whether the geometry field is set.
   */
  @java.lang.Override
  public boolean hasGeometry() {
    return geometry_ != null;
  }
  /**
   * <code>.mojo.geom.Geometry geometry = 3;</code>
   * @return The geometry.
   */
  @java.lang.Override
  public org.mojolang.mojo.geom.Geometry getGeometry() {
    return geometry_ == null ? org.mojolang.mojo.geom.Geometry.getDefaultInstance() : geometry_;
  }
  /**
   * <code>.mojo.geom.Geometry geometry = 3;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.geom.GeometryOrBuilder getGeometryOrBuilder() {
    return getGeometry();
  }

  public static final int BBOX_FIELD_NUMBER = 4;
  private org.mojolang.mojo.geom.BoundingBox bbox_;
  /**
   * <code>.mojo.geom.BoundingBox bbox = 4;</code>
   * @return Whether the bbox field is set.
   */
  @java.lang.Override
  public boolean hasBbox() {
    return bbox_ != null;
  }
  /**
   * <code>.mojo.geom.BoundingBox bbox = 4;</code>
   * @return The bbox.
   */
  @java.lang.Override
  public org.mojolang.mojo.geom.BoundingBox getBbox() {
    return bbox_ == null ? org.mojolang.mojo.geom.BoundingBox.getDefaultInstance() : bbox_;
  }
  /**
   * <code>.mojo.geom.BoundingBox bbox = 4;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.geom.BoundingBoxOrBuilder getBboxOrBuilder() {
    return getBbox();
  }

  public static final int SPATIAL_REFERENCE_FIELD_NUMBER = 5;
  private int spatialReference_;
  /**
   * <code>.mojo.geom.SpatialReference spatial_reference = 5 [(.mojo.alias) = "crs"];</code>
   * @return The enum numeric value on the wire for spatialReference.
   */
  @java.lang.Override public int getSpatialReferenceValue() {
    return spatialReference_;
  }
  /**
   * <code>.mojo.geom.SpatialReference spatial_reference = 5 [(.mojo.alias) = "crs"];</code>
   * @return The spatialReference.
   */
  @java.lang.Override public org.mojolang.mojo.geom.SpatialReference getSpatialReference() {
    @SuppressWarnings("deprecation")
    org.mojolang.mojo.geom.SpatialReference result = org.mojolang.mojo.geom.SpatialReference.valueOf(spatialReference_);
    return result == null ? org.mojolang.mojo.geom.SpatialReference.UNRECOGNIZED : result;
  }

  public static final int PROPERTIES_FIELD_NUMBER = 6;
  private static final class PropertiesDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, org.mojolang.mojo.core.Value> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, org.mojolang.mojo.core.Value>newDefaultInstance(
                org.mojolang.mojo.geom.FeatureProto.internal_static_mojo_geom_Feature_PropertiesEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                org.mojolang.mojo.core.Value.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      java.lang.String, org.mojolang.mojo.core.Value> properties_;
  private com.google.protobuf.MapField<java.lang.String, org.mojolang.mojo.core.Value>
  internalGetProperties() {
    if (properties_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          PropertiesDefaultEntryHolder.defaultEntry);
    }
    return properties_;
  }

  public int getPropertiesCount() {
    return internalGetProperties().getMap().size();
  }
  /**
   * <code>map&lt;string, .mojo.core.Value&gt; properties = 6;</code>
   */

  @java.lang.Override
  public boolean containsProperties(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetProperties().getMap().containsKey(key);
  }
  /**
   * Use {@link #getPropertiesMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, org.mojolang.mojo.core.Value> getProperties() {
    return getPropertiesMap();
  }
  /**
   * <code>map&lt;string, .mojo.core.Value&gt; properties = 6;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, org.mojolang.mojo.core.Value> getPropertiesMap() {
    return internalGetProperties().getMap();
  }
  /**
   * <code>map&lt;string, .mojo.core.Value&gt; properties = 6;</code>
   */
  @java.lang.Override

  public org.mojolang.mojo.core.Value getPropertiesOrDefault(
      java.lang.String key,
      org.mojolang.mojo.core.Value defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, org.mojolang.mojo.core.Value> map =
        internalGetProperties().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .mojo.core.Value&gt; properties = 6;</code>
   */
  @java.lang.Override

  public org.mojolang.mojo.core.Value getPropertiesOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, org.mojolang.mojo.core.Value> map =
        internalGetProperties().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, type_);
    }
    if (id_ != null) {
      output.writeMessage(2, getId());
    }
    if (geometry_ != null) {
      output.writeMessage(3, getGeometry());
    }
    if (bbox_ != null) {
      output.writeMessage(4, getBbox());
    }
    if (spatialReference_ != org.mojolang.mojo.geom.SpatialReference.SPATIAL_REFERENCE_UNSPECIFIED.getNumber()) {
      output.writeEnum(5, spatialReference_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetProperties(),
        PropertiesDefaultEntryHolder.defaultEntry,
        6);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, type_);
    }
    if (id_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getId());
    }
    if (geometry_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getGeometry());
    }
    if (bbox_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getBbox());
    }
    if (spatialReference_ != org.mojolang.mojo.geom.SpatialReference.SPATIAL_REFERENCE_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, spatialReference_);
    }
    for (java.util.Map.Entry<java.lang.String, org.mojolang.mojo.core.Value> entry
         : internalGetProperties().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, org.mojolang.mojo.core.Value>
      properties__ = PropertiesDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, properties__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.mojolang.mojo.geom.Feature)) {
      return super.equals(obj);
    }
    org.mojolang.mojo.geom.Feature other = (org.mojolang.mojo.geom.Feature) obj;

    if (!getType()
        .equals(other.getType())) return false;
    if (hasId() != other.hasId()) return false;
    if (hasId()) {
      if (!getId()
          .equals(other.getId())) return false;
    }
    if (hasGeometry() != other.hasGeometry()) return false;
    if (hasGeometry()) {
      if (!getGeometry()
          .equals(other.getGeometry())) return false;
    }
    if (hasBbox() != other.hasBbox()) return false;
    if (hasBbox()) {
      if (!getBbox()
          .equals(other.getBbox())) return false;
    }
    if (spatialReference_ != other.spatialReference_) return false;
    if (!internalGetProperties().equals(
        other.internalGetProperties())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType().hashCode();
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
    }
    if (hasGeometry()) {
      hash = (37 * hash) + GEOMETRY_FIELD_NUMBER;
      hash = (53 * hash) + getGeometry().hashCode();
    }
    if (hasBbox()) {
      hash = (37 * hash) + BBOX_FIELD_NUMBER;
      hash = (53 * hash) + getBbox().hashCode();
    }
    hash = (37 * hash) + SPATIAL_REFERENCE_FIELD_NUMBER;
    hash = (53 * hash) + spatialReference_;
    if (!internalGetProperties().getMap().isEmpty()) {
      hash = (37 * hash) + PROPERTIES_FIELD_NUMBER;
      hash = (53 * hash) + internalGetProperties().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.mojolang.mojo.geom.Feature parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojolang.mojo.geom.Feature parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojolang.mojo.geom.Feature parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojolang.mojo.geom.Feature parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojolang.mojo.geom.Feature parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojolang.mojo.geom.Feature parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojolang.mojo.geom.Feature parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mojolang.mojo.geom.Feature parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mojolang.mojo.geom.Feature parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.mojolang.mojo.geom.Feature parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mojolang.mojo.geom.Feature parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mojolang.mojo.geom.Feature parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.mojolang.mojo.geom.Feature prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code mojo.geom.Feature}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mojo.geom.Feature)
      org.mojolang.mojo.geom.FeatureOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.mojolang.mojo.geom.FeatureProto.internal_static_mojo_geom_Feature_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetProperties();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetMutableProperties();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.mojolang.mojo.geom.FeatureProto.internal_static_mojo_geom_Feature_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.mojolang.mojo.geom.Feature.class, org.mojolang.mojo.geom.Feature.Builder.class);
    }

    // Construct using org.mojolang.mojo.geom.Feature.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      type_ = "";

      if (idBuilder_ == null) {
        id_ = null;
      } else {
        id_ = null;
        idBuilder_ = null;
      }
      if (geometryBuilder_ == null) {
        geometry_ = null;
      } else {
        geometry_ = null;
        geometryBuilder_ = null;
      }
      if (bboxBuilder_ == null) {
        bbox_ = null;
      } else {
        bbox_ = null;
        bboxBuilder_ = null;
      }
      spatialReference_ = 0;

      internalGetMutableProperties().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.mojolang.mojo.geom.FeatureProto.internal_static_mojo_geom_Feature_descriptor;
    }

    @java.lang.Override
    public org.mojolang.mojo.geom.Feature getDefaultInstanceForType() {
      return org.mojolang.mojo.geom.Feature.getDefaultInstance();
    }

    @java.lang.Override
    public org.mojolang.mojo.geom.Feature build() {
      org.mojolang.mojo.geom.Feature result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.mojolang.mojo.geom.Feature buildPartial() {
      org.mojolang.mojo.geom.Feature result = new org.mojolang.mojo.geom.Feature(this);
      int from_bitField0_ = bitField0_;
      result.type_ = type_;
      if (idBuilder_ == null) {
        result.id_ = id_;
      } else {
        result.id_ = idBuilder_.build();
      }
      if (geometryBuilder_ == null) {
        result.geometry_ = geometry_;
      } else {
        result.geometry_ = geometryBuilder_.build();
      }
      if (bboxBuilder_ == null) {
        result.bbox_ = bbox_;
      } else {
        result.bbox_ = bboxBuilder_.build();
      }
      result.spatialReference_ = spatialReference_;
      result.properties_ = internalGetProperties();
      result.properties_.makeImmutable();
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.mojolang.mojo.geom.Feature) {
        return mergeFrom((org.mojolang.mojo.geom.Feature)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.mojolang.mojo.geom.Feature other) {
      if (other == org.mojolang.mojo.geom.Feature.getDefaultInstance()) return this;
      if (!other.getType().isEmpty()) {
        type_ = other.type_;
        onChanged();
      }
      if (other.hasId()) {
        mergeId(other.getId());
      }
      if (other.hasGeometry()) {
        mergeGeometry(other.getGeometry());
      }
      if (other.hasBbox()) {
        mergeBbox(other.getBbox());
      }
      if (other.spatialReference_ != 0) {
        setSpatialReferenceValue(other.getSpatialReferenceValue());
      }
      internalGetMutableProperties().mergeFrom(
          other.internalGetProperties());
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              type_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getIdFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getGeometryFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getBboxFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 34
            case 40: {
              spatialReference_ = input.readEnum();

              break;
            } // case 40
            case 50: {
              com.google.protobuf.MapEntry<java.lang.String, org.mojolang.mojo.core.Value>
              properties__ = input.readMessage(
                  PropertiesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableProperties().getMutableMap().put(
                  properties__.getKey(), properties__.getValue());
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object type_ = "";
    /**
     * <code>string type = 1;</code>
     * @return The type.
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string type = 1;</code>
     * @return The bytes for type.
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string type = 1;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      
      type_ = getDefaultInstance().getType();
      onChanged();
      return this;
    }
    /**
     * <code>string type = 1;</code>
     * @param value The bytes for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      type_ = value;
      onChanged();
      return this;
    }

    private org.mojolang.mojo.core.Id id_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.core.Id, org.mojolang.mojo.core.Id.Builder, org.mojolang.mojo.core.IdOrBuilder> idBuilder_;
    /**
     * <code>.mojo.core.Id id = 2;</code>
     * @return Whether the id field is set.
     */
    public boolean hasId() {
      return idBuilder_ != null || id_ != null;
    }
    /**
     * <code>.mojo.core.Id id = 2;</code>
     * @return The id.
     */
    public org.mojolang.mojo.core.Id getId() {
      if (idBuilder_ == null) {
        return id_ == null ? org.mojolang.mojo.core.Id.getDefaultInstance() : id_;
      } else {
        return idBuilder_.getMessage();
      }
    }
    /**
     * <code>.mojo.core.Id id = 2;</code>
     */
    public Builder setId(org.mojolang.mojo.core.Id value) {
      if (idBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        id_ = value;
        onChanged();
      } else {
        idBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.mojo.core.Id id = 2;</code>
     */
    public Builder setId(
        org.mojolang.mojo.core.Id.Builder builderForValue) {
      if (idBuilder_ == null) {
        id_ = builderForValue.build();
        onChanged();
      } else {
        idBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.mojo.core.Id id = 2;</code>
     */
    public Builder mergeId(org.mojolang.mojo.core.Id value) {
      if (idBuilder_ == null) {
        if (id_ != null) {
          id_ =
            org.mojolang.mojo.core.Id.newBuilder(id_).mergeFrom(value).buildPartial();
        } else {
          id_ = value;
        }
        onChanged();
      } else {
        idBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.mojo.core.Id id = 2;</code>
     */
    public Builder clearId() {
      if (idBuilder_ == null) {
        id_ = null;
        onChanged();
      } else {
        id_ = null;
        idBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.mojo.core.Id id = 2;</code>
     */
    public org.mojolang.mojo.core.Id.Builder getIdBuilder() {
      
      onChanged();
      return getIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.mojo.core.Id id = 2;</code>
     */
    public org.mojolang.mojo.core.IdOrBuilder getIdOrBuilder() {
      if (idBuilder_ != null) {
        return idBuilder_.getMessageOrBuilder();
      } else {
        return id_ == null ?
            org.mojolang.mojo.core.Id.getDefaultInstance() : id_;
      }
    }
    /**
     * <code>.mojo.core.Id id = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.core.Id, org.mojolang.mojo.core.Id.Builder, org.mojolang.mojo.core.IdOrBuilder> 
        getIdFieldBuilder() {
      if (idBuilder_ == null) {
        idBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.mojolang.mojo.core.Id, org.mojolang.mojo.core.Id.Builder, org.mojolang.mojo.core.IdOrBuilder>(
                getId(),
                getParentForChildren(),
                isClean());
        id_ = null;
      }
      return idBuilder_;
    }

    private org.mojolang.mojo.geom.Geometry geometry_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.geom.Geometry, org.mojolang.mojo.geom.Geometry.Builder, org.mojolang.mojo.geom.GeometryOrBuilder> geometryBuilder_;
    /**
     * <code>.mojo.geom.Geometry geometry = 3;</code>
     * @return Whether the geometry field is set.
     */
    public boolean hasGeometry() {
      return geometryBuilder_ != null || geometry_ != null;
    }
    /**
     * <code>.mojo.geom.Geometry geometry = 3;</code>
     * @return The geometry.
     */
    public org.mojolang.mojo.geom.Geometry getGeometry() {
      if (geometryBuilder_ == null) {
        return geometry_ == null ? org.mojolang.mojo.geom.Geometry.getDefaultInstance() : geometry_;
      } else {
        return geometryBuilder_.getMessage();
      }
    }
    /**
     * <code>.mojo.geom.Geometry geometry = 3;</code>
     */
    public Builder setGeometry(org.mojolang.mojo.geom.Geometry value) {
      if (geometryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        geometry_ = value;
        onChanged();
      } else {
        geometryBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.mojo.geom.Geometry geometry = 3;</code>
     */
    public Builder setGeometry(
        org.mojolang.mojo.geom.Geometry.Builder builderForValue) {
      if (geometryBuilder_ == null) {
        geometry_ = builderForValue.build();
        onChanged();
      } else {
        geometryBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.mojo.geom.Geometry geometry = 3;</code>
     */
    public Builder mergeGeometry(org.mojolang.mojo.geom.Geometry value) {
      if (geometryBuilder_ == null) {
        if (geometry_ != null) {
          geometry_ =
            org.mojolang.mojo.geom.Geometry.newBuilder(geometry_).mergeFrom(value).buildPartial();
        } else {
          geometry_ = value;
        }
        onChanged();
      } else {
        geometryBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.mojo.geom.Geometry geometry = 3;</code>
     */
    public Builder clearGeometry() {
      if (geometryBuilder_ == null) {
        geometry_ = null;
        onChanged();
      } else {
        geometry_ = null;
        geometryBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.mojo.geom.Geometry geometry = 3;</code>
     */
    public org.mojolang.mojo.geom.Geometry.Builder getGeometryBuilder() {
      
      onChanged();
      return getGeometryFieldBuilder().getBuilder();
    }
    /**
     * <code>.mojo.geom.Geometry geometry = 3;</code>
     */
    public org.mojolang.mojo.geom.GeometryOrBuilder getGeometryOrBuilder() {
      if (geometryBuilder_ != null) {
        return geometryBuilder_.getMessageOrBuilder();
      } else {
        return geometry_ == null ?
            org.mojolang.mojo.geom.Geometry.getDefaultInstance() : geometry_;
      }
    }
    /**
     * <code>.mojo.geom.Geometry geometry = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.geom.Geometry, org.mojolang.mojo.geom.Geometry.Builder, org.mojolang.mojo.geom.GeometryOrBuilder> 
        getGeometryFieldBuilder() {
      if (geometryBuilder_ == null) {
        geometryBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.mojolang.mojo.geom.Geometry, org.mojolang.mojo.geom.Geometry.Builder, org.mojolang.mojo.geom.GeometryOrBuilder>(
                getGeometry(),
                getParentForChildren(),
                isClean());
        geometry_ = null;
      }
      return geometryBuilder_;
    }

    private org.mojolang.mojo.geom.BoundingBox bbox_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.geom.BoundingBox, org.mojolang.mojo.geom.BoundingBox.Builder, org.mojolang.mojo.geom.BoundingBoxOrBuilder> bboxBuilder_;
    /**
     * <code>.mojo.geom.BoundingBox bbox = 4;</code>
     * @return Whether the bbox field is set.
     */
    public boolean hasBbox() {
      return bboxBuilder_ != null || bbox_ != null;
    }
    /**
     * <code>.mojo.geom.BoundingBox bbox = 4;</code>
     * @return The bbox.
     */
    public org.mojolang.mojo.geom.BoundingBox getBbox() {
      if (bboxBuilder_ == null) {
        return bbox_ == null ? org.mojolang.mojo.geom.BoundingBox.getDefaultInstance() : bbox_;
      } else {
        return bboxBuilder_.getMessage();
      }
    }
    /**
     * <code>.mojo.geom.BoundingBox bbox = 4;</code>
     */
    public Builder setBbox(org.mojolang.mojo.geom.BoundingBox value) {
      if (bboxBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        bbox_ = value;
        onChanged();
      } else {
        bboxBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.mojo.geom.BoundingBox bbox = 4;</code>
     */
    public Builder setBbox(
        org.mojolang.mojo.geom.BoundingBox.Builder builderForValue) {
      if (bboxBuilder_ == null) {
        bbox_ = builderForValue.build();
        onChanged();
      } else {
        bboxBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.mojo.geom.BoundingBox bbox = 4;</code>
     */
    public Builder mergeBbox(org.mojolang.mojo.geom.BoundingBox value) {
      if (bboxBuilder_ == null) {
        if (bbox_ != null) {
          bbox_ =
            org.mojolang.mojo.geom.BoundingBox.newBuilder(bbox_).mergeFrom(value).buildPartial();
        } else {
          bbox_ = value;
        }
        onChanged();
      } else {
        bboxBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.mojo.geom.BoundingBox bbox = 4;</code>
     */
    public Builder clearBbox() {
      if (bboxBuilder_ == null) {
        bbox_ = null;
        onChanged();
      } else {
        bbox_ = null;
        bboxBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.mojo.geom.BoundingBox bbox = 4;</code>
     */
    public org.mojolang.mojo.geom.BoundingBox.Builder getBboxBuilder() {
      
      onChanged();
      return getBboxFieldBuilder().getBuilder();
    }
    /**
     * <code>.mojo.geom.BoundingBox bbox = 4;</code>
     */
    public org.mojolang.mojo.geom.BoundingBoxOrBuilder getBboxOrBuilder() {
      if (bboxBuilder_ != null) {
        return bboxBuilder_.getMessageOrBuilder();
      } else {
        return bbox_ == null ?
            org.mojolang.mojo.geom.BoundingBox.getDefaultInstance() : bbox_;
      }
    }
    /**
     * <code>.mojo.geom.BoundingBox bbox = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.geom.BoundingBox, org.mojolang.mojo.geom.BoundingBox.Builder, org.mojolang.mojo.geom.BoundingBoxOrBuilder> 
        getBboxFieldBuilder() {
      if (bboxBuilder_ == null) {
        bboxBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.mojolang.mojo.geom.BoundingBox, org.mojolang.mojo.geom.BoundingBox.Builder, org.mojolang.mojo.geom.BoundingBoxOrBuilder>(
                getBbox(),
                getParentForChildren(),
                isClean());
        bbox_ = null;
      }
      return bboxBuilder_;
    }

    private int spatialReference_ = 0;
    /**
     * <code>.mojo.geom.SpatialReference spatial_reference = 5 [(.mojo.alias) = "crs"];</code>
     * @return The enum numeric value on the wire for spatialReference.
     */
    @java.lang.Override public int getSpatialReferenceValue() {
      return spatialReference_;
    }
    /**
     * <code>.mojo.geom.SpatialReference spatial_reference = 5 [(.mojo.alias) = "crs"];</code>
     * @param value The enum numeric value on the wire for spatialReference to set.
     * @return This builder for chaining.
     */
    public Builder setSpatialReferenceValue(int value) {
      
      spatialReference_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.geom.SpatialReference spatial_reference = 5 [(.mojo.alias) = "crs"];</code>
     * @return The spatialReference.
     */
    @java.lang.Override
    public org.mojolang.mojo.geom.SpatialReference getSpatialReference() {
      @SuppressWarnings("deprecation")
      org.mojolang.mojo.geom.SpatialReference result = org.mojolang.mojo.geom.SpatialReference.valueOf(spatialReference_);
      return result == null ? org.mojolang.mojo.geom.SpatialReference.UNRECOGNIZED : result;
    }
    /**
     * <code>.mojo.geom.SpatialReference spatial_reference = 5 [(.mojo.alias) = "crs"];</code>
     * @param value The spatialReference to set.
     * @return This builder for chaining.
     */
    public Builder setSpatialReference(org.mojolang.mojo.geom.SpatialReference value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      spatialReference_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.geom.SpatialReference spatial_reference = 5 [(.mojo.alias) = "crs"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSpatialReference() {
      
      spatialReference_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, org.mojolang.mojo.core.Value> properties_;
    private com.google.protobuf.MapField<java.lang.String, org.mojolang.mojo.core.Value>
    internalGetProperties() {
      if (properties_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            PropertiesDefaultEntryHolder.defaultEntry);
      }
      return properties_;
    }
    private com.google.protobuf.MapField<java.lang.String, org.mojolang.mojo.core.Value>
    internalGetMutableProperties() {
      onChanged();;
      if (properties_ == null) {
        properties_ = com.google.protobuf.MapField.newMapField(
            PropertiesDefaultEntryHolder.defaultEntry);
      }
      if (!properties_.isMutable()) {
        properties_ = properties_.copy();
      }
      return properties_;
    }

    public int getPropertiesCount() {
      return internalGetProperties().getMap().size();
    }
    /**
     * <code>map&lt;string, .mojo.core.Value&gt; properties = 6;</code>
     */

    @java.lang.Override
    public boolean containsProperties(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetProperties().getMap().containsKey(key);
    }
    /**
     * Use {@link #getPropertiesMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, org.mojolang.mojo.core.Value> getProperties() {
      return getPropertiesMap();
    }
    /**
     * <code>map&lt;string, .mojo.core.Value&gt; properties = 6;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, org.mojolang.mojo.core.Value> getPropertiesMap() {
      return internalGetProperties().getMap();
    }
    /**
     * <code>map&lt;string, .mojo.core.Value&gt; properties = 6;</code>
     */
    @java.lang.Override

    public org.mojolang.mojo.core.Value getPropertiesOrDefault(
        java.lang.String key,
        org.mojolang.mojo.core.Value defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, org.mojolang.mojo.core.Value> map =
          internalGetProperties().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .mojo.core.Value&gt; properties = 6;</code>
     */
    @java.lang.Override

    public org.mojolang.mojo.core.Value getPropertiesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, org.mojolang.mojo.core.Value> map =
          internalGetProperties().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearProperties() {
      internalGetMutableProperties().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, .mojo.core.Value&gt; properties = 6;</code>
     */

    public Builder removeProperties(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableProperties().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, org.mojolang.mojo.core.Value>
    getMutableProperties() {
      return internalGetMutableProperties().getMutableMap();
    }
    /**
     * <code>map&lt;string, .mojo.core.Value&gt; properties = 6;</code>
     */
    public Builder putProperties(
        java.lang.String key,
        org.mojolang.mojo.core.Value value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) {
  throw new NullPointerException("map value");
}

      internalGetMutableProperties().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, .mojo.core.Value&gt; properties = 6;</code>
     */

    public Builder putAllProperties(
        java.util.Map<java.lang.String, org.mojolang.mojo.core.Value> values) {
      internalGetMutableProperties().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:mojo.geom.Feature)
  }

  // @@protoc_insertion_point(class_scope:mojo.geom.Feature)
  private static final org.mojolang.mojo.geom.Feature DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.mojolang.mojo.geom.Feature();
  }

  public static org.mojolang.mojo.geom.Feature getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Feature>
      PARSER = new com.google.protobuf.AbstractParser<Feature>() {
    @java.lang.Override
    public Feature parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Feature> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Feature> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.mojolang.mojo.geom.Feature getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

