// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/geom/polygon.proto

package org.mojolang.mojo.geom;

public interface LinearRingCoordinatesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mojo.geom.LinearRingCoordinates)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .mojo.geom.PointCoordinates values = 1;</code>
   */
  java.util.List<org.mojolang.mojo.geom.PointCoordinates> 
      getValuesList();
  /**
   * <code>repeated .mojo.geom.PointCoordinates values = 1;</code>
   */
  org.mojolang.mojo.geom.PointCoordinates getValues(int index);
  /**
   * <code>repeated .mojo.geom.PointCoordinates values = 1;</code>
   */
  int getValuesCount();
  /**
   * <code>repeated .mojo.geom.PointCoordinates values = 1;</code>
   */
  java.util.List<? extends org.mojolang.mojo.geom.PointCoordinatesOrBuilder> 
      getValuesOrBuilderList();
  /**
   * <code>repeated .mojo.geom.PointCoordinates values = 1;</code>
   */
  org.mojolang.mojo.geom.PointCoordinatesOrBuilder getValuesOrBuilder(
      int index);
}
