// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/geom/line_string.proto

// Protobuf Java Version: 3.25.1
package org.mojolang.mojo.geom;

public final class LineStringProto {
  private LineStringProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_geom_LineString_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_geom_LineString_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033mojo/geom/line_string.proto\022\tmojo.geom" +
      "\032\027mojo/geom/lng_lat.proto\032\025mojo/geom/poi" +
      "nt.proto\"B\n\nLineString\022\014\n\004type\030\001 \001(\t\022&\n\013" +
      "coordinates\030\005 \003(\0132\021.mojo.geom.LngLatB\\\n\026" +
      "org.mojolang.mojo.geomB\017LineStringProtoP" +
      "\001Z/github.com/mojo-lang/geom/go/pkg/mojo" +
      "/geom;geomb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.mojolang.mojo.geom.LngLatProto.getDescriptor(),
          org.mojolang.mojo.geom.PointProto.getDescriptor(),
        });
    internal_static_mojo_geom_LineString_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mojo_geom_LineString_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_geom_LineString_descriptor,
        new java.lang.String[] { "Type", "Coordinates", });
    org.mojolang.mojo.geom.LngLatProto.getDescriptor();
    org.mojolang.mojo.geom.PointProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
