// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/geom/lng_lat.proto

// Protobuf Java Version: 3.25.1
package org.mojolang.mojo.geom;

public interface LngLatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mojo.geom.LngLat)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double longitude = 1;</code>
   * @return The longitude.
   */
  double getLongitude();

  /**
   * <code>double latitude = 2;</code>
   * @return The latitude.
   */
  double getLatitude();

  /**
   * <code>double altitude = 3;</code>
   * @return The altitude.
   */
  double getAltitude();
}
