// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/geom/lng_lat.proto

package org.mojolang.mojo.geom;

public final class LngLatProto {
  private LngLatProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_geom_LngLat_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_geom_LngLat_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027mojo/geom/lng_lat.proto\022\tmojo.geom\"?\n\006" +
      "LngLat\022\021\n\tlongitude\030\001 \001(\001\022\020\n\010latitude\030\002 " +
      "\001(\001\022\020\n\010altitude\030\003 \001(\001BX\n\026org.mojolang.mo" +
      "jo.geomB\013LngLatProtoP\001Z/github.com/mojo-" +
      "lang/geom/go/pkg/mojo/geom;geomb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_mojo_geom_LngLat_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mojo_geom_LngLat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_geom_LngLat_descriptor,
        new java.lang.String[] { "Longitude", "Latitude", "Altitude", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
