// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/geom/multi_polygon.proto

package org.mojolang.mojo.geom;

public interface MultiPolygonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mojo.geom.MultiPolygon)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string type = 1;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 1;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>repeated .mojo.geom.Polygon polygons = 5 [(.mojo.alias) = "coordinates"];</code>
   */
  java.util.List<org.mojolang.mojo.geom.Polygon> 
      getPolygonsList();
  /**
   * <code>repeated .mojo.geom.Polygon polygons = 5 [(.mojo.alias) = "coordinates"];</code>
   */
  org.mojolang.mojo.geom.Polygon getPolygons(int index);
  /**
   * <code>repeated .mojo.geom.Polygon polygons = 5 [(.mojo.alias) = "coordinates"];</code>
   */
  int getPolygonsCount();
  /**
   * <code>repeated .mojo.geom.Polygon polygons = 5 [(.mojo.alias) = "coordinates"];</code>
   */
  java.util.List<? extends org.mojolang.mojo.geom.PolygonOrBuilder> 
      getPolygonsOrBuilderList();
  /**
   * <code>repeated .mojo.geom.Polygon polygons = 5 [(.mojo.alias) = "coordinates"];</code>
   */
  org.mojolang.mojo.geom.PolygonOrBuilder getPolygonsOrBuilder(
      int index);
}
