// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/geom/multi_point.proto

package org.mojolang.mojo.geom;

public final class MultiPointProto {
  private MultiPointProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_geom_MultiPoint_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_geom_MultiPoint_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033mojo/geom/multi_point.proto\022\tmojo.geom" +
      "\032\025mojo/geom/point.proto\032\017mojo/mojo.proto" +
      "\"M\n\nMultiPoint\022\014\n\004type\030\001 \001(\t\0221\n\006points\030\005" +
      " \003(\0132\020.mojo.geom.PointB\017\312\317$\013coordinatesB" +
      "\\\n\026org.mojolang.mojo.geomB\017MultiPointPro" +
      "toP\001Z/github.com/mojo-lang/geom/go/pkg/m" +
      "ojo/geom;geomb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.mojolang.mojo.geom.PointProto.getDescriptor(),
          org.mojolang.mojo.MojoProtos.getDescriptor(),
        });
    internal_static_mojo_geom_MultiPoint_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mojo_geom_MultiPoint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_geom_MultiPoint_descriptor,
        new java.lang.String[] { "Type", "Points", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(org.mojolang.mojo.MojoProtos.alias);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    org.mojolang.mojo.geom.PointProto.getDescriptor();
    org.mojolang.mojo.MojoProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
