// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/geom/polygon.proto

package org.mojolang.mojo.geom;

public final class PolygonProto {
  private PolygonProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_geom_Polygon_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_geom_Polygon_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_geom_LinearRingCoordinates_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_geom_LinearRingCoordinates_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_geom_PolygonCoordinates_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_geom_PolygonCoordinates_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027mojo/geom/polygon.proto\022\tmojo.geom\032\033mo" +
      "jo/geom/line_string.proto\032\025mojo/geom/poi" +
      "nt.proto\032\017mojo/mojo.proto\"U\n\007Polygon\022\014\n\004" +
      "type\030\001 \001(\t\022<\n\014line_strings\030\005 \003(\0132\025.mojo." +
      "geom.LineStringB\017\312\317$\013coordinates\"D\n\025Line" +
      "arRingCoordinates\022+\n\006values\030\001 \003(\0132\033.mojo" +
      ".geom.PointCoordinates\"F\n\022PolygonCoordin" +
      "ates\0220\n\006values\030\001 \003(\0132 .mojo.geom.LinearR" +
      "ingCoordinatesBY\n\026org.mojolang.mojo.geom" +
      "B\014PolygonProtoP\001Z/github.com/mojo-lang/g" +
      "eom/go/pkg/mojo/geom;geomb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.mojolang.mojo.geom.LineStringProto.getDescriptor(),
          org.mojolang.mojo.geom.PointProto.getDescriptor(),
          com.google.protobuf.MojoProtos.getDescriptor(),
        });
    internal_static_mojo_geom_Polygon_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mojo_geom_Polygon_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_geom_Polygon_descriptor,
        new java.lang.String[] { "Type", "LineStrings", });
    internal_static_mojo_geom_LinearRingCoordinates_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_mojo_geom_LinearRingCoordinates_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_geom_LinearRingCoordinates_descriptor,
        new java.lang.String[] { "Values", });
    internal_static_mojo_geom_PolygonCoordinates_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_mojo_geom_PolygonCoordinates_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_geom_PolygonCoordinates_descriptor,
        new java.lang.String[] { "Values", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.protobuf.MojoProtos.alias);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    org.mojolang.mojo.geom.LineStringProto.getDescriptor();
    org.mojolang.mojo.geom.PointProto.getDescriptor();
    com.google.protobuf.MojoProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
