// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/geom/polygon.proto

package org.mojolang.mojo.geom;

public interface PolygonCoordinatesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mojo.geom.PolygonCoordinates)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .mojo.geom.LinearRingCoordinates values = 1;</code>
   */
  java.util.List<org.mojolang.mojo.geom.LinearRingCoordinates> 
      getValuesList();
  /**
   * <code>repeated .mojo.geom.LinearRingCoordinates values = 1;</code>
   */
  org.mojolang.mojo.geom.LinearRingCoordinates getValues(int index);
  /**
   * <code>repeated .mojo.geom.LinearRingCoordinates values = 1;</code>
   */
  int getValuesCount();
  /**
   * <code>repeated .mojo.geom.LinearRingCoordinates values = 1;</code>
   */
  java.util.List<? extends org.mojolang.mojo.geom.LinearRingCoordinatesOrBuilder> 
      getValuesOrBuilderList();
  /**
   * <code>repeated .mojo.geom.LinearRingCoordinates values = 1;</code>
   */
  org.mojolang.mojo.geom.LinearRingCoordinatesOrBuilder getValuesOrBuilder(
      int index);
}
