// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/geom/spatial_reference.proto

package org.mojolang.mojo.geom;

public final class SpatialReferenceProto {
  private SpatialReferenceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!mojo/geom/spatial_reference.proto\022\tmoj" +
      "o.geom*\316\001\n\020SpatialReference\022!\n\035SPATIAL_R" +
      "EFERENCE_UNSPECIFIED\020\000\022\034\n\030SPATIAL_REFERE" +
      "NCE_WGS_84\020\001\022\034\n\030SPATIAL_REFERENCE_GCJ_02" +
      "\020\002\022\033\n\027SPATIAL_REFERENCE_BD_09\020\003\022\037\n\033SPATI" +
      "AL_REFERENCE_CGCS_2000\020\004\022\035\n\031SPATIAL_REFE" +
      "RENCE_SH_2000\020\005Bb\n\026org.mojolang.mojo.geo" +
      "mB\025SpatialReferenceProtoP\001Z/github.com/m" +
      "ojo-lang/geom/go/pkg/mojo/geom;geomb\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
