// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/geom/tile/point_tile.proto

package org.mojolang.mojo.geom.tile;

public final class PointTileProto {
  private PointTileProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_geom_tile_PointTile_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_geom_tile_PointTile_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037mojo/geom/tile/point_tile.proto\022\016mojo." +
      "geom.tile\032 mojo/geom/tile/vector_tile.pr" +
      "oto\"\275\001\n\tPointTile\022\017\n\007version\030\017 \001(\005\022\n\n\002id" +
      "\030\001 \001(\t\022\014\n\004type\030\002 \001(\t\022\014\n\004keys\030\003 \003(\t\0220\n\006va" +
      "lues\030\004 \003(\0132 .mojo.geom.tile.VectorTile.V" +
      "alue\022\022\n\nraw_values\030\006 \003(\005\022\013\n\003ids\030\005 \003(\004\022\014\n" +
      "\004tags\030\n \003(\r\022\n\n\002xs\030\013 \003(\005\022\n\n\002ys\030\014 \003(\005Be\n\033o" +
      "rg.mojolang.mojo.geom.tileB\016PointTilePro" +
      "toP\001Z4github.com/mojo-lang/geom/go/pkg/m" +
      "ojo/geom/tile;tileb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.mojolang.mojo.geom.tile.VectorTileProto.getDescriptor(),
        });
    internal_static_mojo_geom_tile_PointTile_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mojo_geom_tile_PointTile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_geom_tile_PointTile_descriptor,
        new java.lang.String[] { "Version", "Id", "Type", "Keys", "Values", "RawValues", "Ids", "Tags", "Xs", "Ys", });
    org.mojolang.mojo.geom.tile.VectorTileProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
