// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/geom/tile/tile_id.proto

package org.mojolang.mojo.geom.tile;

public final class TileIdProto {
  private TileIdProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_geom_tile_TileId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_geom_tile_TileId_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034mojo/geom/tile/tile_id.proto\022\016mojo.geo" +
      "m.tile\"-\n\006TileId\022\t\n\001x\030\001 \001(\005\022\t\n\001y\030\002 \001(\005\022\r" +
      "\n\005level\030\003 \001(\005Bb\n\033org.mojolang.mojo.geom." +
      "tileB\013TileIdProtoP\001Z4github.com/mojo-lan" +
      "g/geom/go/pkg/mojo/geom/tile;tileb\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_mojo_geom_tile_TileId_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mojo_geom_tile_TileId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_geom_tile_TileId_descriptor,
        new java.lang.String[] { "X", "Y", "Level", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
