// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/geom/tile/vector_tile.proto

package org.mojolang.mojo.geom.tile;

public interface VectorTileOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mojo.geom.tile.VectorTile)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .mojo.geom.tile.VectorTile.Layer layers = 3;</code>
   */
  java.util.List<org.mojolang.mojo.geom.tile.VectorTile.Layer> 
      getLayersList();
  /**
   * <code>repeated .mojo.geom.tile.VectorTile.Layer layers = 3;</code>
   */
  org.mojolang.mojo.geom.tile.VectorTile.Layer getLayers(int index);
  /**
   * <code>repeated .mojo.geom.tile.VectorTile.Layer layers = 3;</code>
   */
  int getLayersCount();
  /**
   * <code>repeated .mojo.geom.tile.VectorTile.Layer layers = 3;</code>
   */
  java.util.List<? extends org.mojolang.mojo.geom.tile.VectorTile.LayerOrBuilder> 
      getLayersOrBuilderList();
  /**
   * <code>repeated .mojo.geom.tile.VectorTile.Layer layers = 3;</code>
   */
  org.mojolang.mojo.geom.tile.VectorTile.LayerOrBuilder getLayersOrBuilder(
      int index);
}
